// apps/prism-react/src/app/components/source-catalog.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, Copy, Pencil, Plus, Trash2 } from 'lucide-react';
import { MODE_LABELS, TRANSPORT_LABELS, type BlotterMode, type BlotterSource } from '@macro/prism-core';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useAllSources, useDataSourceStore } from '../data-source-context';
import { AdHocSourceDialog } from './adhoc-source-dialog';

type GroupBy = 'category' | 'transport' | 'mode';

export function SourceCatalog() {
  const store = useDataSourceStore();
  const all = useAllSources();
  const navigate = useNavigate();
  const [groupBy, setGroupBy] = useState<GroupBy>('category');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editSource, setEditSource] = useState<BlotterSource | null>(null);

  const groups = useMemo(() => buildGroups(groupBy, all), [groupBy, all]);

  const open = (src: BlotterSource) => navigate(`/blotter?source=${encodeURIComponent(src.id)}`);
  const addAdhoc = () => {
    setEditSource(null);
    setDialogOpen(true);
  };
  const edit = (src: BlotterSource) => {
    setEditSource(src);
    setDialogOpen(true);
  };

  const modeVariant = (m: BlotterMode): 'success' | 'warning' | 'destructive' =>
    m === 'streaming' ? 'destructive' : m === 'append' ? 'warning' : 'success';

  return (
    <div>
      <header className="flex items-start justify-between gap-4 flex-wrap mb-6">
        <div>
          <h2 className="text-xl font-bold m-0">Data Sources</h2>
          <p className="opacity-70 mt-1">
            Pick a source to open a snapshot + real-time blotter, or define your own ad-hoc source.
          </p>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          <div className="inline-flex rounded-md border overflow-hidden">
            {(['category', 'transport', 'mode'] as GroupBy[]).map((g) => (
              <button
                key={g}
                onClick={() => setGroupBy(g)}
                className={`text-sm px-3 py-1.5 ${groupBy === g ? 'bg-primary text-primary-foreground' : 'bg-background'}`}
              >
                {g === 'category' ? 'Category' : g === 'transport' ? 'Type' : 'Behavior'}
              </button>
            ))}
          </div>
          <Button onClick={addAdhoc}>
            <Plus className="size-4" /> Add ad-hoc source
          </Button>
        </div>
      </header>

      {groups.map((group) => (
        <section key={group.title} className="mb-7">
          <h3 className="text-sm uppercase tracking-wide opacity-60 mb-3">{group.title}</h3>
          <div className="grid gap-4" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(20rem, 1fr))' }}>
            {group.sources.map((src) => (
              <Card key={src.id}>
                <CardContent className="pt-4">
                  <div className="flex gap-1.5 flex-wrap mb-2">
                    <Badge variant="secondary">{TRANSPORT_LABELS[src.transport]}</Badge>
                    <Badge variant={modeVariant(src.mode)}>{MODE_LABELS[src.mode]}</Badge>
                    {src.origin === 'adhoc' && <Badge variant="outline">ad-hoc</Badge>}
                  </div>
                  <h4 className="text-base font-semibold mb-1">{src.name}</h4>
                  <p className="text-sm opacity-70 min-h-10">{src.description}</p>
                  <div className="flex flex-col gap-1 text-xs opacity-70 mt-2">
                    <span>Category: {src.category}</span>
                    {src.topic && <span className="truncate">Topic: {src.topic}</span>}
                  </div>
                </CardContent>
                <CardFooter>
                  <Button size="sm" onClick={() => open(src)}>
                    Open <ArrowRight className="size-4" />
                  </Button>
                  {src.origin === 'adhoc' ? (
                    <>
                      <Button size="icon" variant="ghost" aria-label="Edit" onClick={() => edit(src)}>
                        <Pencil className="size-4" />
                      </Button>
                      <Button size="icon" variant="ghost" aria-label="Delete" onClick={() => store.removeAdhoc(src.id)}>
                        <Trash2 className="size-4" />
                      </Button>
                    </>
                  ) : (
                    <Button
                      size="icon"
                      variant="ghost"
                      aria-label="Duplicate as ad-hoc"
                      title="Duplicate as ad-hoc"
                      onClick={() => edit(src)}
                    >
                      <Copy className="size-4" />
                    </Button>
                  )}
                </CardFooter>
              </Card>
            ))}
          </div>
        </section>
      ))}

      {groups.length === 0 && <p className="opacity-70">No data sources yet — add an ad-hoc source to get started.</p>}

      <AdHocSourceDialog
        open={dialogOpen}
        source={editSource}
        onOpenChange={setDialogOpen}
        onSaved={(src) => {
          setDialogOpen(false);
          open(src);
        }}
      />
    </div>
  );
}

function buildGroups(by: GroupBy, sources: BlotterSource[]): { title: string; sources: BlotterSource[] }[] {
  const labels: Record<string, string> = by === 'transport' ? TRANSPORT_LABELS : by === 'mode' ? MODE_LABELS : {};
  const map = new Map<string, BlotterSource[]>();
  for (const s of sources) {
    const key = by === 'transport' ? s.transport : by === 'mode' ? s.mode : s.category;
    const list = map.get(key) ?? [];
    list.push(s);
    map.set(key, list);
  }
  return [...map.entries()].map(([key, list]) => ({ title: labels[key] ?? key, sources: list }));
}

// apps/prism/src/app/components/source-catalog/source-catalog.component.ts
import { Component, computed, inject, signal, viewChild } from '@angular/core';
import { Router } from '@angular/router';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Card } from 'primeng/card';
import { Tag } from 'primeng/tag';
import { Button } from 'primeng/button';
import { SelectButton } from 'primeng/selectbutton';
import { DataSourceRepository } from '../../services/data-source-repository.service';
import { ActiveSourceService } from '../../services/active-source.service';
import { AdHocSourceDialogComponent } from '../adhoc-source-dialog/adhoc-source-dialog.component';
import {
  MODE_LABELS,
  TRANSPORT_LABELS,
  type BlotterMode,
  type BlotterSource,
} from '@macro/prism-core';

type GroupBy = 'category' | 'transport' | 'mode';

@Component({
  selector: 'app-source-catalog',
  standalone: true,
  imports: [RouterLink, FormsModule, Card, Tag, Button, SelectButton, AdHocSourceDialogComponent],
  templateUrl: './source-catalog.component.html',
  styleUrl: './source-catalog.component.css',
})
export class SourceCatalogComponent {
  private readonly repo = inject(DataSourceRepository);
  private readonly activeSource = inject(ActiveSourceService);
  private readonly router = inject(Router);

  private readonly dialog = viewChild.required(AdHocSourceDialogComponent);

  readonly transportLabels = TRANSPORT_LABELS;
  readonly modeLabels = MODE_LABELS;

  readonly groupByOptions = [
    { label: 'Category', value: 'category' as GroupBy },
    { label: 'Type', value: 'transport' as GroupBy },
    { label: 'Behavior', value: 'mode' as GroupBy },
  ];
  readonly groupBy = signal<GroupBy>('category');

  readonly groups = computed(() => this.buildGroups(this.groupBy(), this.repo.all()));

  open(src: BlotterSource): void {
    this.activeSource.open(src);
    this.router.navigate(['/blotter'], { queryParams: { source: src.id } });
  }

  addAdhoc(): void {
    this.dialog().show();
  }

  edit(src: BlotterSource): void {
    this.dialog().show(src);
  }

  remove(src: BlotterSource): void {
    this.repo.removeAdhoc(src.id);
  }

  onSaved(src: BlotterSource): void {
    this.open(src);
  }

  modeSeverity(mode: BlotterMode): 'success' | 'warn' | 'danger' {
    return mode === 'streaming' ? 'danger' : mode === 'append' ? 'warn' : 'success';
  }

  private buildGroups(by: GroupBy, sources: BlotterSource[]): { title: string; sources: BlotterSource[] }[] {
    if (by === 'category') {
      return this.repo.groupedByCategory().map((g) => ({ title: g.category, sources: g.sources }));
    }
    const labels: Record<string, string> = by === 'transport' ? this.transportLabels : this.modeLabels;
    const map = new Map<string, BlotterSource[]>();
    for (const s of sources) {
      const key = by === 'transport' ? s.transport : s.mode;
      const list = map.get(key) ?? [];
      list.push(s);
      map.set(key, list);
    }
    return [...map.entries()].map(([key, list]) => ({ title: labels[key] ?? key, sources: list }));
  }
}

<div class="catalog">
  <header class="catalog__header">
    <div>
      <h2 class="catalog__title">Data Sources</h2>
      <p class="catalog__subtitle">
        Pick a source to open a snapshot + real-time blotter, or define your own ad-hoc source.
      </p>
    </div>
    <div class="catalog__actions">
      <p-selectButton
        [options]="groupByOptions"
        optionLabel="label"
        optionValue="value"
        [allowEmpty]="false"
        [ngModel]="groupBy()"
        (ngModelChange)="groupBy.set($event)"
      />
      <p-button label="Add ad-hoc source" icon="pi pi-plus" (onClick)="addAdhoc()" />
    </div>
  </header>

  @for (group of groups(); track group.title) {
    <section class="catalog__group">
      <h3 class="catalog__group-title">{{ group.title }}</h3>
      <div class="catalog__grid">
        @for (src of group.sources; track src.id) {
          <p-card styleClass="source-card">
            <div class="source-card__tags">
              <p-tag [value]="transportLabels[src.transport]" severity="secondary" />
              <p-tag [value]="modeLabels[src.mode]" [severity]="modeSeverity(src.mode)" />
              @if (src.origin === 'adhoc') {
                <p-tag value="ad-hoc" severity="info" />
              }
            </div>
            <h4 class="source-card__name">{{ src.name }}</h4>
            <p class="source-card__desc">{{ src.description }}</p>
            <div class="source-card__meta">
              <span><i class="pi pi-tag"></i> {{ src.category }}</span>
              @if (src.topic) {
                <span><i class="pi pi-sitemap"></i> {{ src.topic }}</span>
              }
            </div>
            <div class="source-card__footer">
              <p-button label="Open" icon="pi pi-arrow-right" size="small" (onClick)="open(src)" />
              @if (src.origin === 'adhoc') {
                <p-button
                  icon="pi pi-pencil"
                  [text]="true"
                  severity="secondary"
                  size="small"
                  ariaLabel="Edit"
                  (onClick)="edit(src)"
                />
                <p-button
                  icon="pi pi-trash"
                  [text]="true"
                  severity="danger"
                  size="small"
                  ariaLabel="Delete"
                  (onClick)="remove(src)"
                />
              } @else {
                <p-button
                  icon="pi pi-clone"
                  [text]="true"
                  severity="secondary"
                  size="small"
                  ariaLabel="Duplicate as ad-hoc"
                  (onClick)="duplicate(src)"
                />
              }
            </div>
          </p-card>
        }
      </div>
    </section>
  } @empty {
    <p class="catalog__empty">No data sources yet — add an ad-hoc source to get started.</p>
  }

  <app-adhoc-source-dialog (saved)="onSaved($event)" />
</div>
