// libs/macro-react-grid/src/lib/macro-react-grid.tsx
import { useEffect, useMemo, useState, useRef, useImperativeHandle, forwardRef } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { Subject, Subscription } from 'rxjs';
import {
  ColDef,
  GridOptions,
  GridReadyEvent,
  GridApi,
  GetRowIdParams,
  RowNodeTransaction,
  ModuleRegistry,
  AllCommunityModule,
  Theme,
  colorSchemeDarkBlue,
  colorSchemeLight,
  iconSetAlpine,
  themeAlpine,
} from 'ag-grid-community';
import {
  AllEnterpriseModule,
  IntegratedChartsModule,
} from 'ag-grid-enterprise';
import { AgChartsEnterpriseModule } from 'ag-charts-enterprise';

// Register all ag-Grid modules (Community and Enterprise)
// This ensures all features are available without requiring registration in the application
ModuleRegistry.registerModules([
  AllCommunityModule,
  AllEnterpriseModule,
  IntegratedChartsModule.with(AgChartsEnterpriseModule)
]);

export interface MacroReactGridProps {
  /**
   * Column definitions in JSON format
   * Can be a JSON string or an array of column definition objects
   */
  columns?: string | ColDef[];

  /**
   * Row data for the grid
   */
  rowData?: unknown[];

  /**
   * Grid options (optional)
   */
  gridOptions?: GridOptions;

  /**
   * Function to get row ID for each row
   * This is useful for tracking rows when data changes
   */
  getRowId?: (params: GetRowIdParams) => string;
}

export interface MacroReactGridRef {
  /**
   * Apply transaction to update grid data
   */
  applyTransaction: (transaction: RowNodeTransaction) => void;

  /**
   * Get the grid API instance
   */
  getGridApi: () => GridApi | undefined;

  /**
   * RxJS Subjects for row operations
   */
  addRows$: Subject<unknown[]>;
  updateRows$: Subject<unknown[]>;
  deleteRows$: Subject<unknown[]>;
}

/**
 * Macro React Grid Component
 * Wraps ag-Grid with support for JSON column configuration
 */
export const MacroReactGrid = forwardRef<MacroReactGridRef, MacroReactGridProps>(
  ({ columns = [], rowData = [], gridOptions = {}, getRowId }, ref) => {
    const [theme, setTheme] = useState<Theme | undefined>(undefined);
    const [gridApi, setGridApi] = useState<GridApi | undefined>(undefined);
    const subscriptionsRef = useRef<Subscription>(new Subscription());

    // RxJS Subjects for row operations
    const addRows$ = useRef(new Subject<unknown[]>()).current;
    const updateRows$ = useRef(new Subject<unknown[]>()).current;
    const deleteRows$ = useRef(new Subject<unknown[]>()).current;

  // Default grid options
  const defaultGridOptions: GridOptions = useMemo(
    () => ({
      defaultColDef: {
        sortable: true,
        filter: true,
        resizable: true,
      },
      pagination: true,
      paginationPageSize: 10,
      paginationPageSizeSelector: [10, 25, 50, 100],
      animateRows: true,
      rowSelection: 'multiple',
      suppressRowClickSelection: true,
      enableRangeSelection: true,
      suppressCellFocus: true,
    }),
    []
  );

  // Parse columns from JSON string or use array directly
  const columnDefs: ColDef[] = useMemo(() => {
    if (!columns) {
      return [];
    }

    if (typeof columns === 'string') {
      try {
        const parsed = JSON.parse(columns);
        return Array.isArray(parsed) ? parsed : [parsed];
      } catch (error) {
        console.error('Error parsing columns JSON:', error);
        return [];
      }
    } else if (Array.isArray(columns)) {
      return columns;
    } else {
      return [columns];
    }
  }, [columns]);

  // Merge user-provided grid options with defaults
  const mergedGridOptions: GridOptions = useMemo(
    () => ({
      ...defaultGridOptions,
      ...gridOptions,
      // Ensure columnDefs and rowData are not overridden by gridOptions
      columnDefs: columnDefs,
      rowData: rowData,
      // Add getRowId if provided
      ...(getRowId && { getRowId: getRowId }),
    }),
    [defaultGridOptions, gridOptions, columnDefs, rowData, getRowId]
  );

  // Expose methods and subjects via ref
  useImperativeHandle(ref, () => ({
    applyTransaction: (transaction: RowNodeTransaction) => {
      if (!gridApi) {
        throw new Error('Grid API is not available. Ensure the grid is ready before calling applyTransaction.');
      }
      gridApi.applyTransactionAsync(transaction as any);
    },
    getGridApi: () => gridApi,
    addRows$,
    updateRows$,
    deleteRows$,
  }), [gridApi, addRows$, updateRows$, deleteRows$]);

  // Initialize and update theme based on dark mode
  useEffect(() => {
    const updateTheme = () => {
      const root = document.documentElement;
      const isDark = root.classList.contains('dark');
      
      const baseTheme = themeAlpine;
      let currentTheme: Theme = baseTheme;
      currentTheme = currentTheme.withPart(iconSetAlpine);
      currentTheme = currentTheme.withPart(isDark ? colorSchemeDarkBlue : colorSchemeLight);
      currentTheme = currentTheme.withParams({
        fontFamily: 'Noto Sans',
        headerFontFamily: 'Roboto',
        cellFontFamily: 'Ubuntu',
      });
      setTheme(currentTheme);
    };

    // Initialize theme
    updateTheme();

    // Watch for theme changes
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
          updateTheme();
        }
      });
    });

    const root = document.documentElement;
    observer.observe(root, {
      attributes: true,
      attributeFilter: ['class'],
    });

    return () => {
      observer.disconnect();
    };
  }, []);

  // Setup subscriptions for row operations
  useEffect(() => {
    // Subscribe to addRows$ subject
    subscriptionsRef.current.add(
      addRows$.subscribe((rows) => {
        if (rows && rows.length > 0 && gridApi) {
          gridApi.applyTransactionAsync({
            add: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );

    // Subscribe to updateRows$ subject
    subscriptionsRef.current.add(
      updateRows$.subscribe((rows) => {
        if (rows && rows.length > 0 && gridApi) {
          gridApi.applyTransactionAsync({
            update: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );

    // Subscribe to deleteRows$ subject
    subscriptionsRef.current.add(
      deleteRows$.subscribe((rows) => {
        if (rows && rows.length > 0 && gridApi) {
          gridApi.applyTransactionAsync({
            remove: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );

    // Cleanup subscriptions
    return () => {
      subscriptionsRef.current.unsubscribe();
      subscriptionsRef.current = new Subscription();
    };
  }, [gridApi, addRows$, updateRows$, deleteRows$]);

  /**
   * Grid ready event handler
   */
  const onGridReady = (event: GridReadyEvent): void => {
    setGridApi(event.api);
    console.log('AG Grid is ready', event);
  };

  return (
    <div style={{ height: '100%', width: '100%' }}>
      <AgGridReact
        theme={theme}
        columnDefs={columnDefs}
        enableCharts={true}
        rowData={rowData}
        gridOptions={mergedGridOptions}
        getRowId={getRowId}
        onGridReady={onGridReady}
      />
    </div>
  );
  }
);

MacroReactGrid.displayName = 'MacroReactGrid';

export default MacroReactGrid;

// libs/macro-angular-grid/src/lib/macro-angular-grid/macro-angular-grid.ts
import { Component, Input, OnInit, OnChanges, OnDestroy, SimpleChanges, PLATFORM_ID, inject } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { Subject, Subscription } from 'rxjs';
import { isPlatformBrowser, DOCUMENT } from '@angular/common';
import {
  ColDef,
  GridOptions,
  GridReadyEvent,
  GridApi,
  GetRowIdParams,
  RowNodeTransaction,
  ModuleRegistry,
  AllCommunityModule,
  Theme,
} from 'ag-grid-community';
import {
  AllEnterpriseModule,
  IntegratedChartsModule,
} from 'ag-grid-enterprise';
import {
  colorSchemeDarkBlue,
  colorSchemeLight,
  iconSetAlpine,
  themeAlpine,
} from "ag-grid-community";
import { AgChartsEnterpriseModule } from 'ag-charts-enterprise';

// Register all ag-Grid modules (Community and Enterprise)
// This ensures all features are available without requiring registration in the application
ModuleRegistry.registerModules([
  AllCommunityModule,
  AllEnterpriseModule,
  IntegratedChartsModule.with(AgChartsEnterpriseModule)

]);

/**
 * Macro Angular Grid Component
 * Wraps ag-Grid with support for JSON column configuration
 */
@Component({
  selector: 'lib-macro-angular-grid',
  imports: [AgGridAngular],
  templateUrl: './macro-angular-grid.html',
  styleUrl: './macro-angular-grid.css',
})
export class MacroAngularGrid implements OnInit, OnChanges, OnDestroy {
  /**
   * Column definitions in JSON format
   * Can be a JSON string or an array of column definition objects
   */
  @Input() columns: string | ColDef[] = [];

  /**
   * Row data for the grid
   */
  @Input() rowData: unknown[] = [];

  /**
   * Grid options (optional)
   */
  @Input() gridOptions: GridOptions = {};

  /**
   * Function to get row ID for each row
   * This is useful for tracking rows when data changes
   */
  @Input() getRowId?: (params: GetRowIdParams) => string;

  /**
   * Parsed column definitions
   */
  public columnDefs: ColDef[] = [];

  /**
   * Grid API reference for programmatic access
   */
  private gridApi?: GridApi;

  /**
   * RxJS Subjects for row operations
   * Consumers can publish to these subjects to add/update/delete rows
   */
  public readonly addRows$ = new Subject<unknown[]>();
  public readonly updateRows$ = new Subject<unknown[]>();
  public readonly deleteRows$ = new Subject<unknown[]>();

  /**
   * Subscription management
   */
  private subscriptions = new Subscription();

  /**
   * Theme observer for detecting theme changes
   */
  private themeObserver?: MutationObserver;

  /**
   * Inject dependencies
   */
  private document = inject(DOCUMENT);
  private platformId = inject(PLATFORM_ID);

  /**
   * Default grid options
   */
  public defaultGridOptions: GridOptions = {
    defaultColDef: {
      sortable: true,
      filter: true,
      resizable: true,
    },
    pagination: true,
    paginationPageSize: 10,
    paginationPageSizeSelector: [10, 25, 50, 100],
    animateRows: true,
    rowSelection: 'multiple',
    suppressRowClickSelection: true,
    enableRangeSelection: true,
    suppressCellFocus: true,
  };

  /**
   * Merged grid options
   */
  public mergedGridOptions: GridOptions = {};

  baseTheme = themeAlpine;
  theme : Theme | undefined;

  ngOnInit(): void {
    this.parseColumns();
    this.mergeGridOptions();
    this.initializeTheme();
    this.setupThemeObserver();

    // Subscribe to row operation subjects
    this.setupRowOperationSubscriptions();
  }

  /**
   * Initialize theme based on current dark mode state
   */
  private initializeTheme(): void {
    if (!isPlatformBrowser(this.platformId)) {
      return;
    }

    const root = this.document.documentElement;
    const isDark = root.classList.contains('dark');
    this.updateTheme(isDark);
  }

  /**
   * Update theme based on dark mode
   */
  private updateTheme(isDark: boolean): void {
    this.theme = this.baseTheme;
    this.theme = this.theme.withPart(iconSetAlpine);
    this.theme = this.theme.withPart(isDark ? colorSchemeDarkBlue : colorSchemeLight);
    this.theme = this.theme.withParams({
      fontFamily: 'Noto Sans',
      headerFontFamily: 'Roboto',
      cellFontFamily: 'Ubuntu',
    });
  }

  /**
   * Setup observer to watch for theme changes
   */
  private setupThemeObserver(): void {
    if (!isPlatformBrowser(this.platformId)) {
      return;
    }

    const root = this.document.documentElement;

    // Watch for class changes on document root
    this.themeObserver = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
          const isDark = root.classList.contains('dark');
          this.updateTheme(isDark);
        }
      });
    });

    this.themeObserver.observe(root, {
      attributes: true,
      attributeFilter: ['class'],
    });
  }

  /**
   * Setup subscriptions for row operations
   */
  private setupRowOperationSubscriptions(): void {
    // Subscribe to addRows$ subject
    this.subscriptions.add(
      this.addRows$.subscribe((rows) => {
        if (rows && rows.length > 0) {
          this.applyTransaction({
            add: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );

    // Subscribe to updateRows$ subject
    this.subscriptions.add(
      this.updateRows$.subscribe((rows) => {
        if (rows && rows.length > 0) {
          this.applyTransaction({
            update: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );

    // Subscribe to deleteRows$ subject
    this.subscriptions.add(
      this.deleteRows$.subscribe((rows) => {
        if (rows && rows.length > 0) {
          this.applyTransaction({
            remove: rows as any[],
          } as RowNodeTransaction);
        }
      })
    );
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['columns']) {
      this.parseColumns();
    }
    if (changes['gridOptions'] || changes['getRowId']) {
      this.mergeGridOptions();
    }
  }

  /**
   * Parse columns from JSON string or use array directly
   */
  private parseColumns(): void {
    if (!this.columns) {
      this.columnDefs = [];
      return;
    }

    if (typeof this.columns === 'string') {
      try {
        const parsed = JSON.parse(this.columns);
        this.columnDefs = Array.isArray(parsed) ? parsed : [parsed];
      } catch (error) {
        console.error('Error parsing columns JSON:', error);
        this.columnDefs = [];
      }
    } else if (Array.isArray(this.columns)) {
      this.columnDefs = this.columns;
    } else {
      this.columnDefs = [this.columns];
    }
  }

  /**
   * Merge user-provided grid options with defaults
   */
  private mergeGridOptions(): void {
    this.mergedGridOptions = {
      ...this.defaultGridOptions,
      ...this.gridOptions,
      // Ensure columnDefs and rowData are not overridden by gridOptions
      columnDefs: this.columnDefs,
      rowData: this.rowData,
      // Add getRowId if provided
      ...(this.getRowId && { getRowId: this.getRowId }),
    };
  }

  /**
   * Grid ready event handler
   */
  onGridReady(event: GridReadyEvent): void {
    this.gridApi = event.api;
    console.log('AG Grid is ready', event);
  }

  /**
   * Apply transaction to update grid data
   * This method allows consumers to update grid data programmatically
   *
   * @param transaction - Transaction object with add, update, and/or remove arrays
   *
   * @example
   * ```typescript
   * // Add new rows
   * gridComponent.applyTransaction({
   *   add: [{ id: 5, name: 'New User', age: 25 }]
   * });
   *
   * // Update existing rows
   * gridComponent.applyTransaction({
   *   update: [{ id: 1, name: 'Updated Name', age: 31 }]
   * });
   *
   * // Remove rows
   * gridComponent.applyTransaction({
   *   remove: [{ id: 2 }]
   * });
   *
   * // Combined transaction
   * gridComponent.applyTransaction({
   *   add: [{ id: 6, name: 'New User 2', age: 30 }],
   *   update: [{ id: 1, name: 'Updated Name', age: 31 }],
   *   remove: [{ id: 2 }]
   * });
   * ```
   */
  public applyTransaction(transaction: RowNodeTransaction): void {
    if (!this.gridApi) {
      throw new Error('Grid API is not available. Ensure the grid is ready before calling applyTransaction.');
    }
    this.gridApi.applyTransactionAsync(transaction);
  }

  /**
   * Get the grid API instance
   * @returns GridApi instance or undefined if grid is not ready
   */
  public getGridApi(): GridApi | undefined {
    return this.gridApi;
  }

  /**
   * Cleanup subscriptions
   */
  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
    this.addRows$.complete();
    this.updateRows$.complete();
    this.deleteRows$.complete();
    if (this.themeObserver) {
      this.themeObserver.disconnect();
    }
  }
}
