// apps/prism-react/src/app/components/adhoc-source-dialog.tsx
import { useEffect, useRef, useState } from 'react';
import {
  MODE_LABELS,
  TRANSPORT_LABELS,
  discoverRestTables,
  discoverWsTables,
  type BlotterConnection,
  type BlotterMode,
  type BlotterSource,
  type ColumnMode,
  type RollupConfig,
  type TransportKind,
  type WsTableInfo,
} from '@macro/prism-core';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { useDataSourceStore } from '../data-source-context';

interface FormState {
  name: string;
  category: string;
  transport: TransportKind;
  mode: BlotterMode;
  topic: string;
  filter: string;
  topN: string;
  orderBy: string;
  keyField: string;
  conflationMs: string;
  maxRows: string;
  expandArrays: boolean;
  columnMode: ColumnMode;
  rollupGroupBy: string;
  rollupEnabled: boolean;
  url: string;
  logon: string;
  heartbeat: string;
  servers: string;
  clientName: string;
  stream: string;
  hostUrl: string;
  vpnName: string;
  userName: string;
  password: string;
  wsUrl: string;
  restUrl: string;
}

const EMPTY: FormState = {
  name: '',
  category: 'Custom',
  transport: 'nats',
  mode: 'streaming',
  topic: '',
  filter: '',
  topN: '',
  orderBy: '',
  keyField: '',
  conflationMs: '',
  maxRows: '',
  expandArrays: true,
  columnMode: 'infer',
  rollupGroupBy: '',
  rollupEnabled: false,
  url: '',
  logon: '',
  heartbeat: '',
  servers: '',
  clientName: '',
  stream: '',
  hostUrl: '',
  vpnName: '',
  userName: '',
  password: '',
  wsUrl: '',
  restUrl: '',
};

function fromSource(s: BlotterSource): FormState {
  const c = s.connection;
  return {
    ...EMPTY,
    name: s.name,
    category: s.category,
    transport: s.transport,
    mode: s.mode,
    topic: s.topic,
    filter: s.filter ?? '',
    topN: s.transport === 'amps' ? s.topN?.toString() ?? '' : '',
    orderBy: s.transport === 'amps' ? s.orderBy ?? '' : '',
    keyField: s.keyField ?? '',
    conflationMs: s.conflationMs?.toString() ?? '',
    maxRows: s.maxRows?.toString() ?? '',
    expandArrays: s.expandArrays !== false,
    columnMode: s.columnMode,
    rollupGroupBy: s.rollup?.groupBy.join(', ') ?? '',
    rollupEnabled: !!s.rollup?.enabled,
    url: c.transport === 'amps' ? c.url : '',
    logon: c.transport === 'amps' ? c.logon ?? '' : '',
    heartbeat: c.transport === 'amps' ? c.heartbeat?.toString() ?? '' : '',
    servers: c.transport === 'nats' || c.transport === 'nats-js' ? c.servers : '',
    clientName: c.transport === 'nats' || c.transport === 'nats-js' ? c.name ?? '' : '',
    stream: c.transport === 'nats-js' ? c.stream ?? '' : '',
    hostUrl: c.transport === 'solace' ? c.hostUrl : '',
    vpnName: c.transport === 'solace' ? c.vpnName : '',
    userName: c.transport === 'solace' ? c.userName : '',
    password: c.transport === 'solace' ? c.password : '',
    wsUrl: c.transport === 'websocket' ? c.url : '',
    restUrl: c.transport === 'rest' ? c.url : '',
  };
}

export interface AdHocSourceDialogProps {
  open: boolean;
  source: BlotterSource | null;
  onOpenChange: (open: boolean) => void;
  onSaved: (src: BlotterSource) => void;
}

export function AdHocSourceDialog({ open, source, onOpenChange, onSaved }: AdHocSourceDialogProps) {
  const store = useDataSourceStore();
  const [form, setForm] = useState<FormState>(EMPTY);
  /** Tables announced by a WebSocket/REST table server (null until discovery has run). */
  const [tables, setTables] = useState<WsTableInfo[] | null>(null);
  const [discovering, setDiscovering] = useState(false);
  const [discoverError, setDiscoverError] = useState<string | null>(null);
  /** Bumped per dialog session / URL change so a stale in-flight discovery can't mutate a newer one. */
  const discoverSeq = useRef(0);

  useEffect(() => {
    if (open) {
      // No source = create blank; an ad-hoc source = edit in place; a catalog source = duplicate
      // (form pre-filled, saved as a NEW ad-hoc copy — the catalog itself is read-only).
      const editing = source && source.origin === 'adhoc';
      discoverSeq.current++; // invalidate any in-flight discovery from a previous dialog session
      setForm(source ? (editing ? fromSource(source) : { ...fromSource(source), name: `${source.name} (copy)` }) : EMPTY);
      setDiscovering(false);
      setDiscoverError(null);
      // When opening from an existing WebSocket/REST source, seed the table list with its saved
      // table so the quick-picks show it before (or without) re-discovery.
      setTables(
        (source?.transport === 'websocket' || source?.transport === 'rest') && source.topic
          ? [{ name: source.topic }]
          : null,
      );
    }
  }, [open, source]);

  const set = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((f) => ({ ...f, [key]: value }));

  /** 'table' transports pick a table by name; 'subject' transports subscribe to broker subjects. */
  const family = (t: TransportKind) => (t === 'websocket' || t === 'rest' ? 'table' : 'subject');

  /** User switched transport: reset discovery, drop cross-family topics, pin REST to snapshot-only. */
  const setTransport = (t: TransportKind) => {
    discoverSeq.current++; // discovered tables belong to the previous transport's endpoint
    setTables(null);
    setDiscoverError(null);
    setForm((f) => ({
      ...f,
      transport: t,
      // A broker subject is not a table name (and vice versa) — don't carry it across.
      ...(family(f.transport) !== family(t) ? { topic: '' } : {}),
      // REST is snapshot-only — pin the behavior so append/streaming can't be picked.
      ...(t === 'rest' ? { mode: 'snapshot-update' as BlotterMode } : {}),
    }));
  };

  /** Tables discovered for one URL are meaningless for another — drop them when the URL changes. */
  const setDiscoveryUrl = (key: 'wsUrl' | 'restUrl', url: string) => {
    discoverSeq.current++;
    set(key, url);
    setTables(null);
    setDiscoverError(null);
  };

  /** Adopt the chosen table plus the server's suggested key field / mode (REST stays snapshot-only). */
  const applyTable = (name: string, list: WsTableInfo[] | null) => {
    const table = list?.find((t) => t.name === name);
    setForm((f) => ({
      ...f,
      topic: name,
      ...(table?.keyField ? { keyField: table.keyField } : {}),
      ...(f.transport !== 'rest' && table?.mode && table.mode in MODE_LABELS
        ? { mode: table.mode as BlotterMode }
        : {}),
    }));
  };

  /** Contact the WebSocket/REST endpoint, read the announced tables, and populate the quick-picks. */
  const discoverTables = async () => {
    const isRest = form.transport === 'rest';
    const url = (isRest ? form.restUrl : form.wsUrl).trim();
    if (!url || discovering) return;
    const seq = ++discoverSeq.current;
    setDiscovering(true);
    setDiscoverError(null);
    try {
      const found = (await (isRest ? discoverRestTables(url) : discoverWsTables(url))).filter(
        (t) => typeof t.name === 'string' && t.name.length > 0,
      );
      if (seq !== discoverSeq.current) return; // dialog re-opened / URL changed while in flight
      setTables(found);
      // Auto-pick the first table only when none is set — never clobber a chosen/typed table
      // (functional update: the topic may have been typed while discovery was in flight).
      setForm((f) => {
        if (!found.length || f.topic) return f;
        const t0 = found[0];
        return {
          ...f,
          topic: t0.name,
          ...(t0.keyField ? { keyField: t0.keyField } : {}),
          ...(f.transport !== 'rest' && t0.mode && t0.mode in MODE_LABELS
            ? { mode: t0.mode as BlotterMode }
            : {}),
        };
      });
    } catch (err) {
      if (seq !== discoverSeq.current) return;
      setDiscoverError(err instanceof Error ? err.message : String(err));
    } finally {
      if (seq === discoverSeq.current) setDiscovering(false);
    }
  };

  const isAppend = form.mode === 'append';
  const num = (s: string): number | undefined => (s.trim() === '' ? undefined : Number(s));
  const positiveInt = (s: string): number | undefined => {
    const value = num(s);
    return value != null && Number.isInteger(value) && value > 0 ? value : undefined;
  };

  const canSave = (): boolean => {
    if (!form.name) return false;
    // REST may leave the table blank — the URL itself can be the rows endpoint.
    if (!form.topic && form.transport !== 'rest') return false;
    if (form.mode !== 'append' && !form.keyField) return false;
    switch (form.transport) {
      case 'amps':
        return !!form.url && (form.topN.trim() === '' || positiveInt(form.topN) != null);
      case 'nats':
      case 'nats-js':
        return !!form.servers;
      case 'solace':
        return !!(form.hostUrl && form.vpnName && form.userName);
      case 'websocket':
        return !!form.wsUrl;
      case 'rest':
        return !!form.restUrl;
      default:
        return false;
    }
  };

  const buildConnection = (): BlotterConnection => {
    switch (form.transport) {
      case 'amps':
        return {
          transport: 'amps',
          url: form.url,
          ...(form.logon ? { logon: form.logon } : {}),
          ...(num(form.heartbeat) != null ? { heartbeat: num(form.heartbeat) } : {}),
        };
      case 'nats':
        return { transport: 'nats', servers: form.servers, ...(form.clientName ? { name: form.clientName } : {}) };
      case 'nats-js':
        return {
          transport: 'nats-js',
          servers: form.servers,
          ...(form.clientName ? { name: form.clientName } : {}),
          ...(form.stream ? { stream: form.stream } : {}),
        };
      case 'solace':
        return { transport: 'solace', hostUrl: form.hostUrl, vpnName: form.vpnName, userName: form.userName, password: form.password };
      case 'websocket':
        return { transport: 'websocket', url: form.wsUrl };
      case 'rest':
        return { transport: 'rest', url: form.restUrl };
    }
  };

  /**
   * `"desk, book"` + flag → `{ rollup }` fragment, preserving settings the form doesn't surface.
   * A blank hierarchy with "open rolled up" checked still persists — the blotter opens on the
   * suggested hierarchy.
   */
  const buildRollup = (): { rollup: RollupConfig } | null => {
    const groupBy = form.rollupGroupBy
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
    if (!groupBy.length && !form.rollupEnabled) return null;
    // Keep aggregation overrides / expand levels / grand total from the opened source so an
    // edit/duplicate round-trip doesn't drop them.
    const { groupBy: _g, enabled: _e, ...extras } = source?.rollup ?? { groupBy: [] };
    return { rollup: { ...extras, groupBy, ...(form.rollupEnabled ? { enabled: true } : {}) } };
  };

  const save = () => {
    if (!canSave()) return;
    const payload: Omit<BlotterSource, 'id' | 'origin'> = {
      name: form.name,
      category: form.category || 'Custom',
      transport: form.transport,
      mode: form.mode,
      connection: buildConnection(),
      topic: form.topic,
      columnMode: form.columnMode,
      ...(form.transport === 'amps' && form.filter ? { filter: form.filter } : {}),
      ...(form.transport === 'amps' && positiveInt(form.topN) != null ? { topN: positiveInt(form.topN) } : {}),
      ...(form.transport === 'amps' && form.orderBy.trim() ? { orderBy: form.orderBy.trim() } : {}),
      ...(form.keyField ? { keyField: form.keyField } : {}),
      // Snapshot-only REST has no stream to conflate — drop a value left over from another transport.
      ...(num(form.conflationMs) != null && form.transport !== 'rest' ? { conflationMs: num(form.conflationMs) } : {}),
      ...(isAppend && num(form.maxRows) != null ? { maxRows: num(form.maxRows) } : {}),
      ...(form.expandArrays === false ? { expandArrays: false } : {}),
      ...(buildRollup() ?? {}),
    };
    const editing = source && source.origin === 'adhoc' ? source.id : null;
    let result: BlotterSource;
    if (editing) {
      result = { ...payload, id: editing, origin: 'adhoc' };
      store.updateAdhoc(result);
    } else {
      result = store.addAdhoc(payload);
    }
    onSaved(result);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Ad-hoc data source</DialogTitle>
          <DialogDescription className="sr-only">
            Configure a broker or table connection and how its rows should appear in the blotter.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-3 max-h-[60vh] overflow-auto pr-1">
          <Field label="Name">
            <Input value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="e.g. My FX Quotes" />
          </Field>

          <div className="grid grid-cols-2 gap-3">
            <Field label="Transport">
              <Select value={form.transport} onValueChange={(v) => setTransport(v as TransportKind)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {(Object.keys(TRANSPORT_LABELS) as TransportKind[]).map((t) => (
                    <SelectItem key={t} value={t}>
                      {TRANSPORT_LABELS[t]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </Field>
            <Field label="Behavior">
              {form.transport !== 'rest' ? (
                <Select value={form.mode} onValueChange={(v) => set('mode', v as BlotterMode)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(Object.keys(MODE_LABELS) as BlotterMode[]).map((m) => (
                      <SelectItem key={m} value={m}>
                        {MODE_LABELS[m]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              ) : (
                <span className="text-xs opacity-60 pt-2">
                  Snapshot only — refresh manually from the blotter toolbar.
                </span>
              )}
            </Field>
            <Field label="Category">
              <Input value={form.category} onChange={(e) => set('category', e.target.value)} placeholder="Custom" />
            </Field>
            <Field label="Columns">
              <Select value={form.columnMode} onValueChange={(v) => set('columnMode', v as ColumnMode)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="infer">Smart inference</SelectItem>
                  <SelectItem value="auto-gen">v36 auto-generate</SelectItem>
                </SelectContent>
              </Select>
            </Field>
          </div>

          {form.transport === 'amps' && (
            <>
              <Field label="AMPS URL">
                <Input value={form.url} onChange={(e) => set('url', e.target.value)} placeholder="ws://host:9008/amps/json" />
              </Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Logon (optional)">
                  <Input value={form.logon} onChange={(e) => set('logon', e.target.value)} />
                </Field>
                <Field label="Heartbeat (s)">
                  <Input type="number" value={form.heartbeat} onChange={(e) => set('heartbeat', e.target.value)} />
                </Field>
              </div>
            </>
          )}

          {(form.transport === 'nats' || form.transport === 'nats-js') && (
            <div className="grid grid-cols-2 gap-3">
              <Field label="Servers">
                <Input value={form.servers} onChange={(e) => set('servers', e.target.value)} placeholder="ws://host:9222" />
              </Field>
              <Field label="Client name (optional)">
                <Input value={form.clientName} onChange={(e) => set('clientName', e.target.value)} />
              </Field>
              {form.transport === 'nats-js' && (
                <Field label="Stream (optional)">
                  <Input value={form.stream} onChange={(e) => set('stream', e.target.value)} placeholder="resolved from subject if blank" />
                </Field>
              )}
            </div>
          )}

          {form.transport === 'solace' && (
            <div className="grid grid-cols-2 gap-3">
              <Field label="Host URL">
                <Input value={form.hostUrl} onChange={(e) => set('hostUrl', e.target.value)} placeholder="ws://host:8008" />
              </Field>
              <Field label="VPN">
                <Input value={form.vpnName} onChange={(e) => set('vpnName', e.target.value)} />
              </Field>
              <Field label="User">
                <Input value={form.userName} onChange={(e) => set('userName', e.target.value)} />
              </Field>
              <Field label="Password">
                <Input type="password" value={form.password} onChange={(e) => set('password', e.target.value)} />
              </Field>
            </div>
          )}

          {form.transport === 'websocket' && (
            <Field label="WebSocket URL">
              <div className="flex gap-2">
                <Input
                  className="flex-1"
                  value={form.wsUrl}
                  onChange={(e) => setDiscoveryUrl('wsUrl', e.target.value)}
                  placeholder="ws://localhost:3000/prism"
                />
                <Button type="button" variant="secondary" disabled={!form.wsUrl || discovering} onClick={discoverTables}>
                  {discovering ? 'Loading…' : 'Load tables'}
                </Button>
              </div>
              {discoverError ? (
                <span className="text-xs text-destructive">{discoverError}</span>
              ) : (
                <span className="text-xs opacity-60">
                  The server announces its tables on connect — load them and pick one below.
                </span>
              )}
            </Field>
          )}

          {form.transport === 'rest' && (
            <Field label="REST URL">
              <div className="flex gap-2">
                <Input
                  className="flex-1"
                  value={form.restUrl}
                  onChange={(e) => setDiscoveryUrl('restUrl', e.target.value)}
                  placeholder="http://localhost:3000/prism/tables"
                />
                <Button type="button" variant="secondary" disabled={!form.restUrl || discovering} onClick={discoverTables}>
                  {discovering ? 'Loading…' : 'Load tables'}
                </Button>
              </div>
              {discoverError ? (
                <span className="text-xs text-destructive">{discoverError}</span>
              ) : (
                <span className="text-xs opacity-60">
                  GET the URL for the table catalog; rows come from &lt;url&gt;/&lt;table&gt; as a JSON array.
                  Leave the table blank if the URL itself returns the rows.
                </span>
              )}
            </Field>
          )}

          {form.transport === 'websocket' || form.transport === 'rest' ? (
            <Field label={form.transport === 'rest' ? 'Table (optional)' : 'Table'}>
              <Input
                value={form.topic}
                onChange={(e) => set('topic', e.target.value)}
                placeholder={tables?.length ? 'Pick a table below or type a name' : 'Load tables or type a table name'}
              />
              {tables?.length ? (
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {tables
                    .filter((t) => typeof t.name === 'string' && t.name.length > 0)
                    .map((t) => (
                      <Button
                        key={t.name}
                        type="button"
                        size="sm"
                        variant={form.topic === t.name ? 'default' : 'outline'}
                        title={t.description}
                        onClick={() => applyTable(t.name, tables)}
                      >
                        {t.title ? `${t.title} (${t.name})` : t.name}
                      </Button>
                    ))}
                </div>
              ) : null}
            </Field>
          ) : (
            <Field label={form.transport === 'amps' ? 'Topic' : 'Subject / topic'}>
              <Input value={form.topic} onChange={(e) => set('topic', e.target.value)} placeholder="e.g. macro.fx.quotes.>" />
            </Field>
          )}

          {/* WebSocket/REST table sources always expand arrays — there they are protocol framing. */}
          {form.transport !== 'websocket' && form.transport !== 'rest' && (
            <label className="flex items-start gap-2 cursor-pointer">
              <input
                type="checkbox"
                className="mt-1"
                checked={form.expandArrays}
                onChange={(e) => set('expandArrays', e.target.checked)}
              />
              <span className="flex flex-col gap-0.5">
                <span className="text-sm">Expand array payloads into rows</span>
                <span className="text-xs opacity-60">
                  A message whose payload is a JSON array becomes one row per element. Uncheck to treat the
                  whole array as a single record.
                </span>
              </span>
            </label>
          )}

          <div className="grid grid-cols-2 gap-3">
            {form.transport === 'amps' && (
              <Field label="Filter (optional)">
                <Input value={form.filter} onChange={(e) => set('filter', e.target.value)} placeholder="/status <> 'DONE'" />
              </Field>
            )}
            {!isAppend && (
              <>
                <Field label="Key field">
                  <Input value={form.keyField} onChange={(e) => set('keyField', e.target.value)} placeholder="e.g. symbol" />
                </Field>
                {/* No stream to conflate for snapshot-only REST. */}
                {form.transport !== 'rest' && (
                  <Field label="Conflation (ms, optional)">
                    <Input type="number" value={form.conflationMs} onChange={(e) => set('conflationMs', e.target.value)} />
                  </Field>
                )}
              </>
            )}
            {isAppend && (
              <Field label="Max rows (optional)">
                <Input type="number" value={form.maxRows} onChange={(e) => set('maxRows', e.target.value)} />
              </Field>
            )}
          </div>

          {form.transport === 'amps' && (
            <div className="grid grid-cols-2 gap-3">
              <Field label="Initial SOW Top N (optional)">
                <Input
                  type="number"
                  min={1}
                  step={1}
                  value={form.topN}
                  onChange={(e) => set('topN', e.target.value)}
                  placeholder="e.g. 500"
                />
                {form.topN.trim() && positiveInt(form.topN) == null ? (
                  <span className="text-xs text-destructive">Enter a whole number greater than zero.</span>
                ) : (
                  <span className="text-xs opacity-60">
                    Limits rows returned by the initial SOW query; matching live updates continue.
                  </span>
                )}
              </Field>
              <Field label="Order by (optional)">
                <Input
                  value={form.orderBy}
                  onChange={(e) => set('orderBy', e.target.value)}
                  placeholder="/updatedAt DESC, /symbol ASC"
                />
                <span className="text-xs opacity-60">
                  Comma-separated AMPS fields with optional ASC, DESC, or TEXT directives.
                </span>
              </Field>
            </div>
          )}

          <Field label="Roll-up — group by (optional)">
            <Input
              value={form.rollupGroupBy}
              onChange={(e) => set('rollupGroupBy', e.target.value)}
              placeholder="e.g. desk, book, trader"
            />
            <span className="text-xs opacity-60">
              Comma-separated fields, coarsest first — the blotter groups rows into that hierarchy with
              summed/averaged numeric columns and a grand total. Leave blank and the toolbar's Roll-up
              toggle will suggest one from the data.
            </span>
          </Field>
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              className="mt-1"
              checked={form.rollupEnabled}
              onChange={(e) => set('rollupEnabled', e.target.checked)}
            />
            <span className="flex flex-col gap-0.5">
              <span className="text-sm">Open rolled up</span>
              <span className="text-xs opacity-60">
                Start in the roll-up view instead of the flat tape (uses the suggested hierarchy when
                group-by is blank).
              </span>
            </span>
          </label>
        </div>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button disabled={!canSave()} onClick={save}>
            Open
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-1">
      <Label className="text-xs opacity-70">{label}</Label>
      {children}
    </div>
  );
}

// apps/prism/src/app/components/adhoc-source-dialog/adhoc-source-dialog.component.ts
import { Component, inject, output, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Dialog } from 'primeng/dialog';
import { Select } from 'primeng/select';
import { InputText } from 'primeng/inputtext';
import { InputNumber } from 'primeng/inputnumber';
import { Checkbox } from 'primeng/checkbox';
import { Button } from 'primeng/button';
import { DataSourceRepository } from '../../services/data-source-repository.service';
import {
  MODE_LABELS,
  TRANSPORT_LABELS,
  discoverRestTables,
  discoverWsTables,
  type BlotterConnection,
  type BlotterMode,
  type BlotterSource,
  type ColumnMode,
  type RollupConfig,
  type TransportKind,
  type WsTableInfo,
} from '@macro/prism-core';

@Component({
  selector: 'app-adhoc-source-dialog',
  standalone: true,
  imports: [ReactiveFormsModule, Dialog, Select, InputText, InputNumber, Checkbox, Button],
  templateUrl: './adhoc-source-dialog.component.html',
  styles: [
    `
      .adhoc-form {
        display: flex;
        flex-direction: column;
        gap: 0.85rem;
      }
      .adhoc-form__grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 0.85rem;
      }
      .adhoc-form__row {
        display: flex;
        flex-direction: column;
        gap: 0.3rem;
      }
      .adhoc-form__label {
        font-size: 0.8rem;
        opacity: 0.7;
      }
      .adhoc-form__row input,
      .adhoc-form__row :is(p-select, p-inputnumber) {
        width: 100%;
      }
      .adhoc-form__check {
        flex-direction: row;
        align-items: flex-start;
        gap: 0.6rem;
      }
      .adhoc-form__check-label {
        display: flex;
        flex-direction: column;
        gap: 0.15rem;
        font-size: 0.9rem;
        cursor: pointer;
      }
      .adhoc-form__hint {
        font-size: 0.75rem;
        opacity: 0.6;
      }
      .adhoc-form__inline {
        display: flex;
        gap: 0.5rem;
        align-items: center;
      }
      .adhoc-form__inline input {
        flex: 1;
      }
      .adhoc-form__error {
        font-size: 0.75rem;
        color: var(--p-red-400, #f87171);
      }
    `,
  ],
})
export class AdHocSourceDialogComponent {
  private readonly fb = inject(FormBuilder);
  private readonly repo = inject(DataSourceRepository);

  readonly saved = output<BlotterSource>();
  readonly visible = signal(false);
  private editingId: string | null = null;
  /**
   * Roll-up settings the form doesn't surface (aggregation overrides, expand levels, grand total) —
   * captured from the opened source so an edit/duplicate round-trip doesn't drop them.
   */
  private rollupExtras: Omit<RollupConfig, 'groupBy' | 'enabled'> = {};

  readonly transportOptions = (Object.entries(TRANSPORT_LABELS) as [TransportKind, string][]).map(
    ([value, label]) => ({ value, label }),
  );
  readonly modeOptions = (Object.entries(MODE_LABELS) as [BlotterMode, string][]).map(([value, label]) => ({
    value,
    label,
  }));
  readonly columnModeOptions: { value: ColumnMode; label: string }[] = [
    { value: 'infer', label: 'Smart inference (recommended)' },
    { value: 'auto-gen', label: 'v36 auto-generate' },
  ];

  readonly form = this.fb.nonNullable.group({
    name: ['', Validators.required],
    category: ['Custom', Validators.required],
    transport: ['nats' as TransportKind, Validators.required],
    mode: ['streaming' as BlotterMode, Validators.required],
    topic: ['', Validators.required],
    filter: [''],
    topN: [null as number | null, Validators.min(1)],
    orderBy: [''],
    keyField: [''],
    conflationMs: [null as number | null],
    maxRows: [null as number | null],
    expandArrays: [true],
    columnMode: ['infer' as ColumnMode, Validators.required],
    // Roll-up (optional): comma-separated group-by hierarchy + open-rolled-up flag.
    rollupGroupBy: [''],
    rollupEnabled: [false],
    // AMPS
    url: [''],
    logon: [''],
    heartbeat: [null as number | null],
    // NATS / NATS JetStream
    servers: [''],
    clientName: [''],
    stream: [''],
    // Solace
    hostUrl: [''],
    vpnName: [''],
    userName: [''],
    password: [''],
    // WebSocket
    wsUrl: [''],
    // REST
    restUrl: [''],
  });

  /** Tables announced by a WebSocket/REST table server (null until discovery has run). */
  readonly tables = signal<WsTableInfo[] | null>(null);
  readonly discovering = signal(false);
  readonly discoverError = signal<string | null>(null);
  /** Bumped per dialog session / URL change so a stale in-flight discovery can't mutate a newer one. */
  private discoverEpoch = 0;

  private prevTransport: TransportKind = 'nats';

  constructor() {
    // Tables discovered for one URL are meaningless for another — drop them when the URL changes.
    for (const control of [this.form.controls.wsUrl, this.form.controls.restUrl]) {
      control.valueChanges.pipe(takeUntilDestroyed()).subscribe(() => {
        this.discoverEpoch++;
        this.tables.set(null);
        this.discoverError.set(null);
      });
    }
  }

  /** 'table' transports pick a table by name; 'subject' transports subscribe to broker subjects. */
  private static family(t: TransportKind): 'table' | 'subject' {
    return t === 'websocket' || t === 'rest' ? 'table' : 'subject';
  }

  /** User switched transport (PrimeNG onChange — programmatic patches don't land here). */
  onTransportChange(next: TransportKind): void {
    const familyChanged =
      AdHocSourceDialogComponent.family(this.prevTransport) !== AdHocSourceDialogComponent.family(next);
    this.prevTransport = next;
    // Discovered tables belong to the previous transport's endpoint.
    this.discoverEpoch++;
    this.tables.set(null);
    this.discoverError.set(null);
    // A broker subject is not a table name (and vice versa) — don't carry it across.
    if (familyChanged) this.form.patchValue({ topic: '' });
    // REST is snapshot-only — pin the behavior so append/streaming can't be picked.
    if (next === 'rest') this.form.patchValue({ mode: 'snapshot-update' });
  }

  get transport(): TransportKind {
    return this.form.controls.transport.value;
  }

  get isAppend(): boolean {
    return this.form.controls.mode.value === 'append';
  }

  /**
   * Open the dialog: no arg = create blank; an ad-hoc source = edit in place; a catalog source =
   * duplicate (form pre-filled, saved as a NEW ad-hoc copy — the catalog itself is read-only).
   */
  show(source?: BlotterSource): void {
    this.editingId = source && source.origin === 'adhoc' ? source.id : null;
    this.discoverEpoch++; // invalidate any in-flight discovery from a previous dialog session
    this.discovering.set(false);
    if (source) {
      this.patchFrom(source);
      if (!this.editingId) {
        this.form.patchValue({ name: `${source.name} (copy)` });
      }
    } else {
      this.rollupExtras = {};
      this.form.reset({ category: 'Custom', transport: 'nats', mode: 'streaming', columnMode: 'infer' });
    }
    // After the form patch (which clears discovery state via the URL subscriptions): when opening
    // from a WebSocket/REST source, seed the table list with the saved table so the select shows
    // it before (or without) re-discovery.
    this.discoverError.set(null);
    this.tables.set(
      (source?.transport === 'websocket' || source?.transport === 'rest') && source.topic
        ? [{ name: source.topic }]
        : null,
    );
    this.prevTransport = this.transport;
    this.visible.set(true);
  }

  /** Discovered table names for the editable select — plain strings so the visible text IS the value. */
  tableNames(): string[] {
    return (this.tables() ?? []).map((t) => t.name).filter((n) => typeof n === 'string' && n.length > 0);
  }

  /** Contact the WebSocket/REST endpoint, read the announced tables, and populate the table select. */
  async discoverTables(): Promise<void> {
    const isRest = this.transport === 'rest';
    const url = (isRest ? this.form.controls.restUrl.value : this.form.controls.wsUrl.value).trim();
    if (!url || this.discovering()) return;
    const epoch = ++this.discoverEpoch;
    this.discovering.set(true);
    this.discoverError.set(null);
    try {
      const tables = await (isRest ? discoverRestTables(url) : discoverWsTables(url));
      if (epoch !== this.discoverEpoch) return; // dialog re-opened / URL changed while in flight
      this.tables.set(tables);
      // Auto-pick the first table only when none is set — never clobber a chosen/typed table.
      if (tables.length && !this.form.controls.topic.value) {
        this.applyTableSuggestions(tables[0].name);
      }
    } catch (err) {
      if (epoch !== this.discoverEpoch) return;
      this.discoverError.set(err instanceof Error ? err.message : String(err));
    } finally {
      if (epoch === this.discoverEpoch) this.discovering.set(false);
    }
  }

  /** onChange of the editable table select: adopt suggestions only for real option picks. */
  onTableChange(event: { originalEvent?: Event; value?: unknown }): void {
    // Typing in the editable input also fires onChange (per keystroke) — the form control already
    // tracks the text, and a half-typed name must not adopt another table's key field / mode.
    if (event.originalEvent?.type === 'input') return;
    if (typeof event.value === 'string' && event.value) this.applyTableSuggestions(event.value);
  }

  /** Adopt the chosen table plus the server's suggested key field / mode (REST stays snapshot-only). */
  private applyTableSuggestions(name: string): void {
    this.form.patchValue({ topic: name });
    const table = this.tables()?.find((t) => t.name === name);
    if (!table) return;
    if (table.keyField) this.form.patchValue({ keyField: table.keyField });
    if (this.transport !== 'rest' && table.mode && table.mode in MODE_LABELS) {
      this.form.patchValue({ mode: table.mode as BlotterMode });
    }
  }

  canSave(): boolean {
    const v = this.form.getRawValue();
    if (!v.name) return false;
    // REST may leave the table blank — the URL itself can be the rows endpoint.
    if (!v.topic && v.transport !== 'rest') return false;
    if (v.mode !== 'append' && !v.keyField) return false;
    if (v.transport === 'amps' && v.topN != null && (!Number.isInteger(v.topN) || v.topN < 1)) return false;
    switch (v.transport) {
      case 'amps':
        return !!v.url;
      case 'nats':
      case 'nats-js':
        return !!v.servers;
      case 'solace':
        return !!(v.hostUrl && v.vpnName && v.userName);
      case 'websocket':
        return !!v.wsUrl;
      case 'rest':
        return !!v.restUrl;
      default:
        return false;
    }
  }

  save(): void {
    if (!this.canSave()) return;
    const v = this.form.getRawValue();
    const payload: Omit<BlotterSource, 'id' | 'origin'> = {
      name: v.name,
      category: v.category || 'Custom',
      transport: v.transport,
      mode: v.mode,
      connection: this.buildConnection(),
      topic: v.topic,
      columnMode: v.columnMode,
      ...(v.transport === 'amps' && v.filter ? { filter: v.filter } : {}),
      ...(v.transport === 'amps' && v.topN != null ? { topN: v.topN } : {}),
      ...(v.transport === 'amps' && v.orderBy.trim() ? { orderBy: v.orderBy.trim() } : {}),
      ...(v.keyField ? { keyField: v.keyField } : {}),
      // Snapshot-only REST has no stream to conflate — drop a value left over from another transport.
      ...(v.conflationMs != null && v.transport !== 'rest' ? { conflationMs: v.conflationMs } : {}),
      ...(v.mode === 'append' && v.maxRows != null ? { maxRows: v.maxRows } : {}),
      ...(v.expandArrays === false ? { expandArrays: false } : {}),
      ...(this.buildRollup(v.rollupGroupBy, v.rollupEnabled) ?? {}),
    };
    const result = this.editingId
      ? this.updateExisting(this.editingId, payload)
      : this.repo.addAdhoc(payload);
    this.visible.set(false);
    this.saved.emit(result);
  }

  cancel(): void {
    this.visible.set(false);
  }

  /**
   * `"desk, book"` + flag → `{ rollup }` fragment (with preserved extras). A blank hierarchy with
   * "open rolled up" checked still persists — the blotter opens on the suggested hierarchy.
   */
  private buildRollup(groupByText: string, enabled: boolean): { rollup: RollupConfig } | null {
    const groupBy = groupByText
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
    if (!groupBy.length && !enabled) return null;
    return { rollup: { ...this.rollupExtras, groupBy, ...(enabled ? { enabled: true } : {}) } };
  }

  private updateExisting(id: string, payload: Omit<BlotterSource, 'id' | 'origin'>): BlotterSource {
    const updated: BlotterSource = { ...payload, id, origin: 'adhoc' };
    this.repo.updateAdhoc(updated);
    return updated;
  }

  private buildConnection(): BlotterConnection {
    const v = this.form.getRawValue();
    switch (v.transport) {
      case 'amps':
        return {
          transport: 'amps',
          url: v.url,
          ...(v.logon ? { logon: v.logon } : {}),
          ...(v.heartbeat != null ? { heartbeat: v.heartbeat } : {}),
        };
      case 'nats':
        return { transport: 'nats', servers: v.servers, ...(v.clientName ? { name: v.clientName } : {}) };
      case 'nats-js':
        return {
          transport: 'nats-js',
          servers: v.servers,
          ...(v.clientName ? { name: v.clientName } : {}),
          ...(v.stream ? { stream: v.stream } : {}),
        };
      case 'solace':
        return {
          transport: 'solace',
          hostUrl: v.hostUrl,
          vpnName: v.vpnName,
          userName: v.userName,
          password: v.password ?? '',
        };
      case 'websocket':
        return { transport: 'websocket', url: v.wsUrl };
      case 'rest':
        return { transport: 'rest', url: v.restUrl };
    }
  }

  private patchFrom(source: BlotterSource): void {
    const c = source.connection;
    const { groupBy: _groupBy, enabled: _enabled, ...rollupExtras } = source.rollup ?? { groupBy: [] };
    this.rollupExtras = rollupExtras;
    this.form.reset({
      name: source.name,
      category: source.category,
      transport: source.transport,
      mode: source.mode,
      topic: source.topic,
      filter: source.filter ?? '',
      topN: source.topN ?? null,
      orderBy: source.orderBy ?? '',
      keyField: source.keyField ?? '',
      conflationMs: source.conflationMs ?? null,
      maxRows: source.maxRows ?? null,
      expandArrays: source.expandArrays !== false,
      columnMode: source.columnMode,
      rollupGroupBy: source.rollup?.groupBy.join(', ') ?? '',
      rollupEnabled: !!source.rollup?.enabled,
      url: c.transport === 'amps' ? c.url : '',
      logon: c.transport === 'amps' ? c.logon ?? '' : '',
      heartbeat: c.transport === 'amps' ? c.heartbeat ?? null : null,
      servers: c.transport === 'nats' || c.transport === 'nats-js' ? c.servers : '',
      clientName: c.transport === 'nats' || c.transport === 'nats-js' ? c.name ?? '' : '',
      stream: c.transport === 'nats-js' ? c.stream ?? '' : '',
      hostUrl: c.transport === 'solace' ? c.hostUrl : '',
      vpnName: c.transport === 'solace' ? c.vpnName : '',
      userName: c.transport === 'solace' ? c.userName : '',
      password: c.transport === 'solace' ? c.password : '',
      wsUrl: c.transport === 'websocket' ? c.url : '',
      restUrl: c.transport === 'rest' ? c.url : '',
    });
  }
}

<p-dialog
  header="Ad-hoc data source"
  [modal]="true"
  [style]="{ width: '36rem' }"
  [visible]="visible()"
  (visibleChange)="visible.set($event)"
>
  <form [formGroup]="form" class="adhoc-form">
    <div class="adhoc-form__row">
      <span class="adhoc-form__label">Name</span>
      <input pInputText formControlName="name" placeholder="e.g. My FX Quotes" />
    </div>

    <div class="adhoc-form__grid">
      <div class="adhoc-form__row">
        <span class="adhoc-form__label">Transport</span>
        <p-select
          formControlName="transport"
          [options]="transportOptions"
          optionLabel="label"
          optionValue="value"
          (onChange)="onTransportChange($event.value)"
        />
      </div>
      <div class="adhoc-form__row">
        <span class="adhoc-form__label">Behavior</span>
        @if (transport !== 'rest') {
          <p-select formControlName="mode" [options]="modeOptions" optionLabel="label" optionValue="value" />
        } @else {
          <span class="adhoc-form__hint">Snapshot only — refresh manually from the blotter toolbar.</span>
        }
      </div>
      <div class="adhoc-form__row">
        <span class="adhoc-form__label">Category</span>
        <input pInputText formControlName="category" placeholder="Custom" />
      </div>
      <div class="adhoc-form__row">
        <span class="adhoc-form__label">Columns</span>
        <p-select formControlName="columnMode" [options]="columnModeOptions" optionLabel="label" optionValue="value" />
      </div>
    </div>

    <!-- Connection (per transport) -->
    @switch (transport) {
      @case ('amps') {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">AMPS URL</span>
          <input pInputText formControlName="url" placeholder="ws://host:9008/amps/json" />
        </div>
        <div class="adhoc-form__grid">
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Logon (optional)</span>
            <input pInputText formControlName="logon" />
          </div>
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Heartbeat (s)</span>
            <p-inputnumber formControlName="heartbeat" [min]="0" />
          </div>
        </div>
      }
      @case ('websocket') {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">WebSocket URL</span>
          <div class="adhoc-form__inline">
            <input pInputText formControlName="wsUrl" placeholder="ws://localhost:3000/prism" />
            <p-button
              label="Load tables"
              icon="pi pi-list"
              severity="secondary"
              [loading]="discovering()"
              [disabled]="!form.controls.wsUrl.value"
              (onClick)="discoverTables()"
            />
          </div>
          @if (discoverError(); as err) {
            <span class="adhoc-form__error">{{ err }}</span>
          } @else {
            <span class="adhoc-form__hint">
              The server announces its tables on connect — load them and pick one below.
            </span>
          }
        </div>
      }
      @case ('rest') {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">REST URL</span>
          <div class="adhoc-form__inline">
            <input pInputText formControlName="restUrl" placeholder="http://localhost:3000/prism/tables" />
            <p-button
              label="Load tables"
              icon="pi pi-list"
              severity="secondary"
              [loading]="discovering()"
              [disabled]="!form.controls.restUrl.value"
              (onClick)="discoverTables()"
            />
          </div>
          @if (discoverError(); as err) {
            <span class="adhoc-form__error">{{ err }}</span>
          } @else {
            <span class="adhoc-form__hint">
              GET the URL for the table catalog; rows come from <code>&lt;url&gt;/&lt;table&gt;</code> as a
              JSON array. Leave the table blank if the URL itself returns the rows.
            </span>
          }
        </div>
      }
      @case ('solace') {
        <div class="adhoc-form__grid">
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Host URL</span>
            <input pInputText formControlName="hostUrl" placeholder="ws://host:8008" />
          </div>
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">VPN</span>
            <input pInputText formControlName="vpnName" />
          </div>
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">User</span>
            <input pInputText formControlName="userName" />
          </div>
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Password</span>
            <input pInputText type="password" formControlName="password" />
          </div>
        </div>
      }
      @default {
        <!-- nats / nats-js -->
        <div class="adhoc-form__grid">
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Servers</span>
            <input pInputText formControlName="servers" placeholder="ws://host:8224" />
          </div>
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Client name (optional)</span>
            <input pInputText formControlName="clientName" />
          </div>
          @if (transport === 'nats-js') {
            <div class="adhoc-form__row">
              <span class="adhoc-form__label">Stream (optional)</span>
              <input pInputText formControlName="stream" placeholder="resolved from subject if blank" />
            </div>
          }
        </div>
      }
    }

    <div class="adhoc-form__row">
      @if (transport === 'websocket' || transport === 'rest') {
        <span class="adhoc-form__label">{{ transport === 'rest' ? 'Table (optional)' : 'Table' }}</span>
        <p-select
          formControlName="topic"
          [options]="tableNames()"
          [editable]="true"
          placeholder="Load tables or type a table name"
          (onChange)="onTableChange($event)"
        />
      } @else {
        <span class="adhoc-form__label">{{ transport === 'amps' ? 'Topic' : 'Subject / topic' }}</span>
        <input pInputText formControlName="topic" placeholder="e.g. macro.fx.quotes.>" />
      }
    </div>

    @if (transport !== 'websocket' && transport !== 'rest') {
      <!-- WebSocket/REST table sources always expand arrays — there they are protocol framing. -->
      <div class="adhoc-form__row adhoc-form__check">
        <p-checkbox formControlName="expandArrays" [binary]="true" inputId="expandArrays" />
        <label for="expandArrays" class="adhoc-form__check-label">
          Expand array payloads into rows
          <span class="adhoc-form__hint">
            A message whose payload is a JSON array becomes one row per element. Uncheck to treat the
            whole array as a single record.
          </span>
        </label>
      </div>
    }

    <div class="adhoc-form__grid">
      @if (transport === 'amps') {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">Filter (optional)</span>
          <input pInputText formControlName="filter" placeholder="/status &lt;&gt; 'DONE'" />
        </div>
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">Initial SOW Top N (optional)</span>
          <p-inputnumber
            formControlName="topN"
            [min]="1"
            [step]="1"
            [useGrouping]="false"
            [minFractionDigits]="0"
            [maxFractionDigits]="0"
            placeholder="e.g. 500"
          />
          <span class="adhoc-form__hint">Limits rows returned by the initial SOW query; matching live updates continue.</span>
        </div>
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">Order by (optional)</span>
          <input pInputText formControlName="orderBy" placeholder="/orderDate DESC, /customerName ASC" />
          <span class="adhoc-form__hint">Comma-separated: /field [ASC | DESC] [TEXT]</span>
        </div>
      }
      @if (!isAppend) {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">Key field</span>
          <input pInputText formControlName="keyField" placeholder="e.g. symbol" />
        </div>
        @if (transport !== 'rest') {
          <!-- No stream to conflate for snapshot-only REST. -->
          <div class="adhoc-form__row">
            <span class="adhoc-form__label">Conflation (ms, optional)</span>
            <p-inputnumber formControlName="conflationMs" [min]="0" />
          </div>
        }
      }
      @if (isAppend) {
        <div class="adhoc-form__row">
          <span class="adhoc-form__label">Max rows (optional)</span>
          <p-inputnumber formControlName="maxRows" [min]="1" />
        </div>
      }
    </div>

    <div class="adhoc-form__row">
      <span class="adhoc-form__label">Roll-up — group by (optional)</span>
      <input pInputText formControlName="rollupGroupBy" placeholder="e.g. desk, book, trader" />
      <span class="adhoc-form__hint">
        Comma-separated fields, coarsest first — the blotter groups rows into that hierarchy with
        summed/averaged numeric columns and a grand total. Leave blank and the toolbar's Roll-up
        toggle will suggest one from the data.
      </span>
    </div>
    <div class="adhoc-form__row adhoc-form__check">
      <p-checkbox formControlName="rollupEnabled" [binary]="true" inputId="rollupEnabled" />
      <label for="rollupEnabled" class="adhoc-form__check-label">
        Open rolled up
        <span class="adhoc-form__hint">
          Start in the roll-up view instead of the flat tape (uses the suggested hierarchy when
          group-by is blank).
        </span>
      </label>
    </div>
  </form>

  <ng-template #footer>
    <p-button label="Cancel" [text]="true" severity="secondary" (onClick)="cancel()" />
    <p-button label="Open" icon="pi pi-arrow-right" [disabled]="!canSave()" (onClick)="save()" />
  </ng-template>
</p-dialog>
