// apps/prism/src/app/components/blotter/blotter.component.ts
import { Component, OnDestroy, computed, effect, inject, signal, viewChild } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map } from 'rxjs/operators';
import type { ColDef, GetRowIdParams, GridOptions } from 'ag-grid-community';
import { Button } from 'primeng/button';
import { Tag } from 'primeng/tag';
import { SelectButton } from 'primeng/selectbutton';
import { Message } from 'primeng/message';
import { Popover } from 'primeng/popover';
import { InputText } from 'primeng/inputtext';
import { FormsModule } from '@angular/forms';
import { MacroAngularGrid } from '@macro/macro-angular-grid';
import type { ColumnFormatMap } from '@macro/macro-grid-format';
import {
  BlotterFeed,
  MODE_LABELS,
  TRANSPORT_LABELS,
  applyInferredFormats,
  applyRollupToColumns,
  completeRollup,
  inferColumns,
  rollupGridOptions,
  suggestRollup,
  type BlotterMode,
  type BlotterSource,
  type ColumnMode,
  type FeedState,
  type FeedStatus,
  type GridOps,
  type RollupConfig,
} from '@macro/prism-core';
import { DataSourceRepository } from '../../services/data-source-repository.service';
import { ActiveSourceService } from '../../services/active-source.service';
import { AdHocSourceDialogComponent } from '../adhoc-source-dialog/adhoc-source-dialog.component';

type Row = Record<string, unknown>;

@Component({
  selector: 'app-blotter',
  standalone: true,
  imports: [RouterLink, FormsModule, MacroAngularGrid, Button, Tag, SelectButton, Message, Popover, InputText, AdHocSourceDialogComponent],
  templateUrl: './blotter.component.html',
  styleUrl: './blotter.component.css',
})
export class BlotterComponent implements OnDestroy {
  private readonly grid = viewChild(MacroAngularGrid);
  private readonly picker = viewChild.required<Popover>('picker');
  private readonly dialog = viewChild.required(AdHocSourceDialogComponent);
  private readonly repo = inject(DataSourceRepository);
  private readonly activeSource = inject(ActiveSourceService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  readonly transportLabels = TRANSPORT_LABELS;
  readonly modeLabels = MODE_LABELS;

  readonly source = signal<BlotterSource | null>(null);
  readonly columns = signal<ColDef[]>([]);
  readonly formats = signal<ColumnFormatMap>({});
  readonly columnMode = signal<ColumnMode>('infer');
  readonly showGrid = signal(true);

  /** Active roll-up config: the source's own, else a suggestion inferred from the first record. */
  readonly rollup = signal<RollupConfig | null>(null);
  /** Whether the roll-up view is on (seeded from `source.rollup.enabled`, toggled from the toolbar). */
  readonly rollupOn = signal(false);
  /** A usable roll-up exists (a source config with a blank hierarchy waits for the suggestion). */
  readonly hasRollup = computed(() => (this.rollup()?.groupBy.length ?? 0) > 0);
  /** The config to actually group by, or null when the view is off / the config has no hierarchy. */
  private readonly activeRollup = computed<RollupConfig | null>(() =>
    this.rollupOn() && this.hasRollup() ? this.rollup() : null,
  );

  /** Columns actually bound to the grid — decorated with rowGroup/aggFunc when rolled up. */
  readonly effectiveColumns = computed<ColDef[]>(() => {
    const cols = this.columns();
    const r = this.activeRollup();
    return r ? applyRollupToColumns(cols, r) : cols;
  });

  /** Filter text for the source picker popover. */
  readonly pickerFilter = signal('');

  /** Sources grouped by category, narrowed by the picker's filter text. */
  readonly pickerGroups = computed(() => {
    const q = this.pickerFilter().trim().toLowerCase();
    const groups = this.repo.groupedByCategory();
    if (!q) return groups;
    return groups
      .map((g) => ({
        category: g.category,
        sources: g.sources.filter(
          (s) =>
            s.name.toLowerCase().includes(q) ||
            s.category.toLowerCase().includes(q) ||
            s.topic.toLowerCase().includes(q) ||
            this.transportLabels[s.transport].toLowerCase().includes(q),
        ),
      }))
      .filter((g) => g.sources.length > 0);
  });

  /** Mirror of the framework-free feed state into a signal so the template stays reactive. */
  private readonly feedState = signal<FeedState>({ status: 'idle', rowCount: 0, msgsPerSec: 0, error: null });

  readonly columnModeOptions = [
    { label: 'Infer', value: 'infer' as ColumnMode },
    { label: 'Auto (v36)', value: 'auto-gen' as ColumnMode },
  ];

  /** Seed the wrapper's format store only on the infer path; auto-gen formats via the callback. */
  readonly seedFormats = computed<ColumnFormatMap>(() => (this.columnMode() === 'infer' ? this.formats() : {}));

  readonly gridOptions = computed<GridOptions>(() => {
    const r = this.activeRollup();
    const rollupOpts: GridOptions = r
      ? {
          ...rollupGridOptions(r),
          // The wrapper's status-bar Grouping toggle / the row-group panel can clear every group
          // inside the grid — flip the roll-up view off with them so the toolbar stays honest
          // (and the remount removes the grand-total footer + unhides the group columns).
          onColumnRowGroupChanged: (e) => {
            // Only user gestures (status-bar toggle → 'api', panel drag → 'uiColumnDragged', …).
            // Our own columnDefs pushes arrive as 'gridOptionsChanged' and must not flip the view
            // (e.g. the transient empty-columns push while a feed restarts).
            if (e.source === 'gridOptionsChanged' || e.source === 'gridInitializing') return;
            if (!this.rollupOn() || e.api.getRowGroupColumns().length > 0) return;
            setTimeout(() => {
              this.rollupOn.set(false);
              this.restartGrid();
            }, 0);
          },
        }
      : {};
    if (this.columnMode() !== 'auto-gen') return rollupOpts;
    const formatDefs = applyInferredFormats(this.formats());
    return {
      ...rollupOpts,
      autoGenerateColumnDefs: { objectValues: 'flatten', nullishValues: 'include' },
      // Auto-gen columns never pass through `columns` — decorate the generated defs instead.
      // Read the signal at call time: generation runs synchronously with the first data batch,
      // before change detection re-delivers the config completed in onFirstRecord.
      processAutoGeneratedColumnDefs: (params) => {
        const defs = formatDefs(params) ?? params.columnDefs;
        const current = this.activeRollup();
        return current ? applyRollupToColumns(defs, current) : defs;
      },
    };
  });

  private feed?: BlotterFeed;
  private feedUnsub?: () => void;

  /** `?source=<id>` from the URL — the deep-link / layout-persisted source for this instance. */
  private readonly routeSourceId = toSignal(
    this.route.queryParamMap.pipe(map((pm) => pm.get('source'))),
    { initialValue: this.route.snapshot.queryParamMap.get('source') },
  );

  /** Reactive resolution of the URL id against the (async-loaded) repo + the in-memory active source. */
  private readonly resolvedSource = computed<BlotterSource | null>(() => {
    const id = this.routeSourceId();
    const all = this.repo.all(); // re-resolve once the catalog finishes loading
    if (id) return all.find((s) => s.id === id) ?? this.activeSource.active();
    return this.activeSource.active();
  });

  /** Last source id we (re)built a feed for; guards the effect against redundant restarts. */
  private appliedId: string | null | undefined = undefined;

  constructor() {
    // Switch the blotter in place whenever the resolved source changes (URL nav from the picker,
    // deep link, or catalog load). Each switch tears down the old feed and remounts the grid.
    effect(() => {
      const src = this.resolvedSource();
      const id = src?.id ?? null;
      if (id === this.appliedId) return;
      this.appliedId = id;
      this.applySource(src);
    });
  }

  readonly getRowId = (params: GetRowIdParams): string => {
    const src = this.source();
    const data = params.data as Row;
    if (src?.mode === 'append') return String(data['__id']);
    return String(data[src?.keyField ?? '__id']);
  };

  get status(): FeedStatus {
    return this.feedState().status;
  }
  get rowCount(): number {
    return this.feedState().rowCount;
  }
  get msgsPerSec(): number {
    return this.feedState().msgsPerSec;
  }
  get error(): string | null {
    return this.feedState().error;
  }

  statusSeverity(): 'success' | 'danger' | 'warn' | 'secondary' {
    switch (this.status) {
      case 'live':
        return 'success';
      case 'error':
        return 'danger';
      case 'connecting':
      case 'snapshot-loading':
        return 'warn';
      default:
        return 'secondary';
    }
  }

  ngOnDestroy(): void {
    this.feedUnsub?.();
    this.feed?.stop();
  }

  setColumnMode(mode: ColumnMode): void {
    if (mode === this.columnMode()) return;
    this.columnMode.set(mode);
    this.restartGrid(); // rebuild the grid with the new column strategy
  }

  /** Flat tape ⇄ rolled-up view. Remounts the grid so grouping options settle at creation. */
  toggleRollup(): void {
    if (!this.hasRollup()) return;
    this.rollupOn.set(!this.rollupOn());
    this.restartGrid();
  }

  reconnect(): void {
    if (this.source()) this.restartGrid();
  }

  disconnect(): void {
    this.feed?.stop();
  }

  /** Snapshot-only REST sources: re-fetch and diff the snapshot into the grid in place. */
  refreshSnapshot(): void {
    void this.feed?.refresh();
  }

  // ── source picker ──

  /** Switch this blotter instance to another source (drives the URL so it persists in layouts). */
  switchSource(src: BlotterSource): void {
    this.picker().hide();
    if (src.id === this.source()?.id) return;
    this.activeSource.open(src);
    this.router.navigate(['/blotter'], { queryParams: { source: src.id } });
  }

  newSource(): void {
    this.picker().hide();
    this.dialog().show();
  }

  editSource(src: BlotterSource, event: Event): void {
    event.stopPropagation();
    this.picker().hide();
    this.dialog().show(src);
  }

  /** Catalog sources are read-only — open the dialog pre-filled to save an editable ad-hoc copy. */
  duplicateSource(src: BlotterSource, event: Event): void {
    event.stopPropagation();
    this.picker().hide();
    this.dialog().show(src);
  }

  /** Delete an ad-hoc source; if it's the one on screen, drop back to the empty-state picker. */
  removeSource(src: BlotterSource, event: Event): void {
    event.stopPropagation();
    const wasActive = src.id === this.source()?.id;
    this.repo.removeAdhoc(src.id);
    if (wasActive) {
      this.activeSource.clear();
      this.router.navigate(['/blotter']);
    }
  }

  /** A new/edited ad-hoc source was saved from the dialog — open it. */
  onSourceSaved(src: BlotterSource): void {
    if (src.id === this.source()?.id) {
      // Edited the active source in place — switchSource would no-op on the same id, leaving the
      // old connection settings and roll-up running. Re-apply the saved source directly.
      this.applySource(src);
      return;
    }
    this.switchSource(src);
  }

  private applySource(src: BlotterSource | null): void {
    this.feedUnsub?.();
    this.feed?.stop();
    this.source.set(src);
    this.rollup.set(src?.rollup ?? null);
    this.rollupOn.set(!!src?.rollup?.enabled);
    if (!src) {
      this.showGrid.set(false);
      return;
    }
    this.columnMode.set(src.columnMode);
    this.restartGrid();
  }

  /** Remount the grid (setInitialRowData is one-shot per grid instance), then start the feed. */
  private restartGrid(): void {
    this.feedUnsub?.();
    this.feed?.stop();
    // Drop the old feed's columns now so the new grid doesn't mount with stale defs that the
    // feed start then clears (a visible flash, and a spurious group-removal event when rolled up).
    this.columns.set([]);
    this.showGrid.set(false);
    setTimeout(() => {
      this.showGrid.set(true);
      setTimeout(() => this.startFeed(), 0);
    }, 0);
  }

  private startFeed(): void {
    const src = this.source();
    const grid = this.grid();
    if (!src || !grid) return;
    this.columns.set([]);
    // Adapt the Angular grid's Subjects/method to the framework-free GridOps interface.
    const ops: GridOps = {
      addRows: (rows) => grid.addRows$.next(rows),
      updateRows: (rows) => grid.updateRows$.next(rows),
      deleteRows: (rows) => grid.deleteRows$.next(rows),
      setInitialRowData: (rows) => grid.setInitialRowData(rows),
    };
    const feed = new BlotterFeed(src, ops, (rec) => this.onFirstRecord(rec));
    this.feed = feed;
    this.feedState.set(feed.getState());
    this.feedUnsub = feed.subscribe(() => this.feedState.set(feed.getState()));
    feed.start();
  }

  private onFirstRecord(rec: Row): void {
    const src = this.source();
    const { columns, formats } = inferColumns(rec, src?.keyField);
    this.formats.set(formats);
    if (this.columnMode() === 'infer') this.columns.set(columns);
    // An explicit source hierarchy wins (completed with inferred aggregations for the fields it
    // doesn't cover); otherwise — including "open rolled up" saved with a blank hierarchy —
    // suggest one from the inferred columns so the toolbar toggle works on any payload with
    // plausible grouping fields.
    if (src?.rollup?.groupBy.length) {
      this.rollup.set(completeRollup(src.rollup, columns));
    } else {
      this.rollup.set(suggestRollup(columns, { keyField: src?.keyField, mode: src?.mode }));
    }
  }

  modeSeverity(mode: BlotterMode): 'success' | 'warn' | 'danger' {
    return mode === 'streaming' ? 'danger' : mode === 'append' ? 'warn' : 'success';
  }
}

<div class="blotter">
  <div class="blotter__bar">
    @if (source(); as src) {
      <button type="button" class="source-trigger" (click)="picker.toggle($event)" aria-label="Change data source">
        <span class="source-trigger__name">{{ src.name }}</span>
        <p-tag [value]="transportLabels[src.transport]" severity="secondary" />
        <p-tag [value]="modeLabels[src.mode]" [severity]="modeSeverity(src.mode)" />
        <i class="pi pi-chevron-down source-trigger__caret"></i>
      </button>

      <div class="blotter__status">
        <p-tag [value]="status" [severity]="statusSeverity()" />
        <span class="blotter__metric">{{ rowCount }} rows</span>
        @if (src.transport !== 'rest') {
          <!-- Snapshot-only REST has no stream — a frozen "0 msg/s" would read like a dead feed. -->
          <span class="blotter__metric">{{ msgsPerSec }} msg/s</span>
        }
      </div>

      <div class="blotter__actions">
        <p-selectButton
          [options]="columnModeOptions"
          optionLabel="label"
          optionValue="value"
          [allowEmpty]="false"
          [ngModel]="columnMode()"
          (ngModelChange)="setColumnMode($event)"
        />
        <p-button
          icon="pi pi-sitemap"
          label="Roll-up"
          size="small"
          [outlined]="!rollupOn()"
          [disabled]="!hasRollup()"
          [title]="hasRollup() ? (rollupOn() ? 'Back to the flat view' : 'Group with subtotals (Risk/PnL style)') : 'No grouping fields detected yet'"
          (onClick)="toggleRollup()"
        />
        @if (src.transport === 'rest') {
          <p-button
            icon="pi pi-sync"
            label="Refresh"
            size="small"
            [disabled]="status !== 'live' && status !== 'error'"
            (onClick)="refreshSnapshot()"
          />
        }
        <p-button icon="pi pi-refresh" label="Reconnect" [text]="true" size="small" (onClick)="reconnect()" />
        <p-button
          icon="pi pi-stop"
          label="Disconnect"
          [text]="true"
          severity="secondary"
          size="small"
          (onClick)="disconnect()"
        />
      </div>
    } @else {
      <button type="button" class="source-trigger source-trigger--empty" (click)="picker.toggle($event)">
        <i class="pi pi-database"></i>
        <span>Select data source</span>
        <i class="pi pi-chevron-down source-trigger__caret"></i>
      </button>
    }
  </div>

  @if (source()) {
    @if (error; as err) {
      <p-message severity="error">{{ err }}</p-message>
    }

    <div class="blotter__grid">
      @if (showGrid()) {
        <lib-macro-angular-grid
          [columns]="effectiveColumns()"
          [columnFormats]="seedFormats()"
          [gridOptions]="gridOptions()"
          [getRowId]="getRowId"
        />
      }
    </div>
  } @else {
    <div class="blotter__empty">
      <i class="pi pi-database blotter__empty-icon"></i>
      <p class="blotter__empty-title">No data source selected</p>
      <p class="blotter__empty-hint">Pick a configured source — or define your own — to start the blotter.</p>
      <div class="blotter__empty-actions">
        <p-button label="Select data source" icon="pi pi-list" (onClick)="picker.toggle($event)" />
        <p-button label="New data source" icon="pi pi-plus" [outlined]="true" (onClick)="newSource()" />
      </div>
    </div>
  }
</div>

<!-- Subtle, in-place source picker shared by the toolbar trigger and the empty state. -->
<p-popover #picker [dismissable]="true" styleClass="source-picker" (onShow)="searchInput.focus()">
  <div class="picker">
    <input
      #searchInput
      pInputText
      type="text"
      class="picker__search"
      placeholder="Search data sources…"
      [ngModel]="pickerFilter()"
      (ngModelChange)="pickerFilter.set($event)"
    />
    <div class="picker__list">
      @for (group of pickerGroups(); track group.category) {
        <div class="picker__group">{{ group.category }}</div>
        @for (src of group.sources; track src.id) {
          <div class="picker__item" [class.picker__item--active]="src.id === source()?.id">
            <button type="button" class="picker__item-main" (click)="switchSource(src)">
              <span class="picker__item-name">{{ src.name }}</span>
              <span class="picker__item-tags">
                <p-tag [value]="transportLabels[src.transport]" severity="secondary" />
                <p-tag [value]="modeLabels[src.mode]" [severity]="modeSeverity(src.mode)" />
                @if (src.origin === 'adhoc') {
                  <p-tag value="ad-hoc" severity="info" />
                }
              </span>
            </button>
            @if (src.origin === 'adhoc') {
              <span class="picker__item-actions">
                <button type="button" class="picker__icon-btn" aria-label="Edit" (click)="editSource(src, $event)">
                  <i class="pi pi-pencil"></i>
                </button>
                <button type="button" class="picker__icon-btn picker__icon-btn--danger" aria-label="Delete" (click)="removeSource(src, $event)">
                  <i class="pi pi-trash"></i>
                </button>
              </span>
            } @else {
              <span class="picker__item-actions">
                <button
                  type="button"
                  class="picker__icon-btn"
                  aria-label="Duplicate as ad-hoc"
                  title="Duplicate as ad-hoc"
                  (click)="duplicateSource(src, $event)"
                >
                  <i class="pi pi-clone"></i>
                </button>
              </span>
            }
          </div>
        }
      } @empty {
        <p class="picker__empty">No sources match “{{ pickerFilter() }}”.</p>
      }
    </div>
    <div class="picker__footer">
      <p-button label="New data source" icon="pi pi-plus" size="small" (onClick)="newSource()" />
      <a routerLink="/sources" class="picker__browse" (click)="picker.hide()">Browse all</a>
    </div>
  </div>
</p-popover>

<app-adhoc-source-dialog (saved)="onSourceSaved($event)" />

// apps/prism-react/src/app/components/blotter.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ChevronDown, Database, ListTree, Plus, RefreshCw, RotateCw, Square } from 'lucide-react';
import type { ColDef, GetRowIdParams, GridOptions } from 'ag-grid-community';
import { MacroReactGrid, type MacroReactGridRef } from '@macro/macro-react-grid';
import type { ColumnFormatMap } from '@macro/macro-grid-format';
import {
  BlotterFeed,
  MODE_LABELS,
  TRANSPORT_LABELS,
  applyInferredFormats,
  applyRollupToColumns,
  completeRollup,
  inferColumns,
  rollupGridOptions,
  suggestRollup,
  type BlotterMode,
  type BlotterSource,
  type ColumnMode,
  type FeedState,
  type GridOps,
  type RollupConfig,
} from '@macro/prism-core';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useAllSources, useDataSourceStore } from '../data-source-context';
import { SourcePicker } from './source-picker';
import { AdHocSourceDialog } from './adhoc-source-dialog';

type Row = Record<string, unknown>;
const IDLE: FeedState = { status: 'idle', rowCount: 0, msgsPerSec: 0, error: null };

const modeVariant = (m: BlotterMode): 'success' | 'warning' | 'destructive' =>
  m === 'streaming' ? 'destructive' : m === 'append' ? 'warning' : 'success';

export function Blotter() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const sourceId = params.get('source');
  // Reactive over the store so the blotter follows ad-hoc edits/deletes and the async catalog load.
  const all = useAllSources();
  const source = useMemo(
    () => (sourceId ? all.find((s) => s.id === sourceId) ?? null : null),
    [all, sourceId],
  );

  const gridRef = useRef<MacroReactGridRef>(null);
  const feedRef = useRef<BlotterFeed | null>(null);

  const [columnMode, setColumnMode] = useState<ColumnMode>('infer');
  const [modeSourceId, setModeSourceId] = useState<string | null>(null);
  const [columns, setColumns] = useState<ColDef[]>([]);
  const [formats, setFormats] = useState<ColumnFormatMap>({});
  const [rowData, setRowData] = useState<unknown[]>([]);
  const [feedState, setFeedState] = useState<FeedState>(IDLE);
  const [reconnectNonce, setReconnectNonce] = useState(0);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editSource, setEditSource] = useState<BlotterSource | null>(null);
  /** Active roll-up config: the source's own, else a suggestion inferred from the first record. */
  const [rollup, setRollup] = useState<RollupConfig | null>(null);
  const [rollupOn, setRollupOn] = useState(false);

  // When SWITCHING to a different source, adopt its default column mode + roll-up. Done during
  // render (not in an effect) so the state is settled before the feed effect runs — avoids a
  // double feed restart. Editing the same source in place keeps the user's current toggles.
  if (source && source.id !== modeSourceId) {
    setModeSourceId(source.id);
    setColumnMode(source.columnMode);
    setRollup(source.rollup ?? null);
    setRollupOn(!!source.rollup?.enabled);
  }

  // Remount the grid on every feed (re)start so AG Grid init-only options (getRowId, the auto-gen
  // column strategy, grouping options) are re-applied. Keyed by source + column mode + roll-up
  // view + an explicit reconnect/edit nonce.
  const gridKey = `${source?.id ?? 'none'}:${columnMode}:${rollupOn ? 'rollup' : 'flat'}:${reconnectNonce}`;

  const switchSource = (src: BlotterSource) => navigate(`/blotter?source=${encodeURIComponent(src.id)}`);
  const openNew = () => {
    setEditSource(null);
    setDialogOpen(true);
  };
  const openEdit = (src: BlotterSource) => {
    setEditSource(src);
    setDialogOpen(true);
  };

  const getRowId = useCallback(
    (p: GetRowIdParams) => {
      const data = p.data as Row;
      if (source?.mode === 'append') return String(data['__id']);
      return String(data[source?.keyField ?? '__id']);
    },
    [source],
  );

  /** A usable roll-up exists (a source config with a blank hierarchy waits for the suggestion). */
  const hasRollup = (rollup?.groupBy.length ?? 0) > 0;
  /** The config to actually group by, or null when the view is off / the config has no hierarchy. */
  const activeRollup = rollupOn && hasRollup ? rollup : null;
  /**
   * Live-read mirror for the auto-gen callback: column generation runs when the first data batch
   * hits the grid, potentially before React re-renders with the config completed in the feed's
   * first-record callback — a plain closure would decorate with the stale partial config.
   */
  const activeRollupRef = useRef(activeRollup);
  activeRollupRef.current = activeRollup;

  /** Stable identity so the grid wrapper's restore-on-change effect only fires on real changes. */
  const seedFormats = useMemo<ColumnFormatMap>(
    () => (columnMode === 'infer' ? formats : {}),
    [columnMode, formats],
  );

  /** Columns actually bound to the grid — decorated with rowGroup/aggFunc when rolled up. */
  const effectiveColumns = useMemo(
    () => (activeRollup ? applyRollupToColumns(columns, activeRollup) : columns),
    [columns, activeRollup],
  );

  const gridOptions = useMemo<GridOptions>(() => {
    const r = activeRollup;
    const rollupOpts: GridOptions = r
      ? {
          ...rollupGridOptions(r),
          // The wrapper's status-bar Grouping toggle / the row-group panel can clear every group
          // inside the grid — flip the roll-up view off with them so the toolbar stays honest
          // (the state flip remounts the grid flat via gridKey).
          onColumnRowGroupChanged: (e) => {
            // Only user gestures (status-bar toggle → 'api', panel drag → 'uiColumnDragged', …).
            // Our own columnDefs pushes arrive as 'gridOptionsChanged' and must not flip the view
            // (e.g. the transient empty-columns push while a feed restarts).
            if (e.source === 'gridOptionsChanged' || e.source === 'gridInitializing') return;
            if (e.api.getRowGroupColumns().length > 0) return;
            setTimeout(() => setRollupOn(false), 0);
          },
        }
      : {};
    if (columnMode !== 'auto-gen') return rollupOpts;
    const formatDefs = applyInferredFormats(formats);
    return {
      ...rollupOpts,
      autoGenerateColumnDefs: { objectValues: 'flatten', nullishValues: 'include' },
      // Auto-gen columns never pass through `columns` — decorate the generated defs instead
      // (via the ref so generation sees the freshest config; see activeRollupRef).
      processAutoGeneratedColumnDefs: (params) => {
        const defs = formatDefs(params) ?? params.columnDefs;
        const current = activeRollupRef.current;
        return current ? applyRollupToColumns(defs, current) : defs;
      },
    };
  }, [columnMode, formats, activeRollup]);

  // Create + start the feed when the source / column mode / remount key changes.
  useEffect(() => {
    const grid = gridRef.current;
    if (!source || !grid) return;
    setColumns([]);
    setRowData([]);
    setFeedState(IDLE);

    const ops: GridOps = {
      addRows: (rows) => grid.addRows$.next(rows),
      updateRows: (rows) => grid.updateRows$.next(rows),
      deleteRows: (rows) => grid.deleteRows$.next(rows),
      // The React grid has no setInitialRowData — seed via the rowData prop state.
      setInitialRowData: (rows) => setRowData(rows),
    };
    const feed = new BlotterFeed(source, ops, (rec) => {
      const inferred = inferColumns(rec, source.keyField);
      setFormats(inferred.formats);
      if (columnMode !== 'auto-gen') setColumns(inferred.columns);
      // An explicit source hierarchy wins (completed with inferred aggregations for the fields it
      // doesn't cover); otherwise — including "open rolled up" saved with a blank hierarchy —
      // suggest one from the inferred columns.
      if (source.rollup?.groupBy.length) {
        setRollup(completeRollup(source.rollup, inferred.columns));
      } else {
        setRollup(suggestRollup(inferred.columns, { keyField: source.keyField, mode: source.mode }));
      }
    });
    feedRef.current = feed;
    const off = feed.subscribe(() => setFeedState(feed.getState()));
    setFeedState(feed.getState());
    void feed.start();

    return () => {
      off();
      void feed.stop();
      feedRef.current = null;
    };
  }, [source, columnMode, rollupOn, reconnectNonce]);

  const reconnect = () => setReconnectNonce((n) => n + 1);
  const disconnect = () => void feedRef.current?.stop();
  const switchMode = (mode: ColumnMode) => {
    if (mode === columnMode) return;
    setColumnMode(mode); // gridKey includes columnMode, so this remounts with the new strategy
  };

  const sourceDialog = (
    <AdHocSourceDialog
      open={dialogOpen}
      source={editSource}
      onOpenChange={setDialogOpen}
      onSaved={(src) => {
        setDialogOpen(false);
        setReconnectNonce((n) => n + 1); // remount even when editing the active source in place
        // Editing the active source in place keeps the same id, so the render-time adoption
        // block won't fire — adopt the (possibly changed) roll-up config explicitly.
        if (src.id === sourceId) {
          setRollup(src.rollup ?? null);
          setRollupOn(!!src.rollup?.enabled);
        }
        switchSource(src);
      }}
    />
  );

  if (!source) {
    return (
      <div className="flex flex-col items-center gap-3 pt-16 text-center">
        <Database className="size-9 opacity-40" />
        <p className="font-semibold text-lg m-0">No data source selected</p>
        <p className="opacity-70 m-0">Pick a configured source — or define your own — to start the blotter.</p>
        <div className="flex gap-2 mt-4">
          <SourcePicker
            activeId={null}
            onSelect={switchSource}
            onNew={openNew}
            onEdit={openEdit}
            onDuplicate={openEdit} // the dialog turns a catalog source into a new ad-hoc copy
            trigger={
              <Button>
                Select data source <ChevronDown className="size-4" />
              </Button>
            }
          />
          <Button variant="outline" onClick={openNew}>
            <Plus className="size-4" /> New data source
          </Button>
        </div>
        {sourceDialog}
      </div>
    );
  }

  const statusVariant =
    feedState.status === 'live'
      ? 'success'
      : feedState.status === 'error'
        ? 'destructive'
        : feedState.status === 'connecting' || feedState.status === 'snapshot-loading'
          ? 'warning'
          : 'secondary';

  return (
    <div className="flex flex-col h-full gap-3">
      <div className="flex items-center gap-3 flex-wrap">
        <SourcePicker
          activeId={source.id}
          onSelect={switchSource}
          onNew={openNew}
          onEdit={openEdit}
          onDuplicate={openEdit} // the dialog turns a catalog source into a new ad-hoc copy
          trigger={
            <button
              type="button"
              aria-label="Change data source"
              className="flex items-center gap-2 -ml-2 rounded-md border border-transparent px-2 py-1 hover:bg-accent hover:border-border"
            >
              <span className="font-bold text-lg">{source.name}</span>
              <Badge variant="secondary">{TRANSPORT_LABELS[source.transport]}</Badge>
              <Badge variant={modeVariant(source.mode)}>{MODE_LABELS[source.mode]}</Badge>
              <ChevronDown className="size-3.5 opacity-60" />
            </button>
          }
        />

        <div className="flex items-center gap-3">
          <Badge variant={statusVariant}>{feedState.status}</Badge>
          <span className="text-sm opacity-70">{feedState.rowCount} rows</span>
          {/* Snapshot-only REST has no stream — a frozen "0 msg/s" would read like a dead feed. */}
          {source.transport !== 'rest' && <span className="text-sm opacity-70">{feedState.msgsPerSec} msg/s</span>}
        </div>

        <div className="ml-auto flex items-center gap-2 flex-wrap">
          <div className="inline-flex rounded-md border overflow-hidden">
            {(['infer', 'auto-gen'] as ColumnMode[]).map((m) => (
              <button
                key={m}
                onClick={() => switchMode(m)}
                className={`text-sm px-3 py-1.5 ${columnMode === m ? 'bg-primary text-primary-foreground' : 'bg-background'}`}
              >
                {m === 'infer' ? 'Infer' : 'Auto (v36)'}
              </button>
            ))}
          </div>
          <Button
            variant={rollupOn ? 'default' : 'outline'}
            size="sm"
            disabled={!hasRollup}
            title={
              hasRollup
                ? rollupOn
                  ? 'Back to the flat view'
                  : 'Group with subtotals (Risk/PnL style)'
                : 'No grouping fields detected yet'
            }
            onClick={() => setRollupOn((v) => !v)}
          >
            <ListTree className="size-4" /> Roll-up
          </Button>
          {source.transport === 'rest' && (
            <Button
              size="sm"
              disabled={feedState.status !== 'live' && feedState.status !== 'error'}
              onClick={() => void feedRef.current?.refresh()}
            >
              <RotateCw className="size-4" /> Refresh
            </Button>
          )}
          <Button variant="ghost" size="sm" onClick={reconnect}>
            <RefreshCw className="size-4" /> Reconnect
          </Button>
          <Button variant="ghost" size="sm" onClick={disconnect}>
            <Square className="size-4" /> Disconnect
          </Button>
        </div>
      </div>

      {feedState.error && (
        <div className="rounded-md border border-destructive bg-destructive/10 text-destructive px-3 py-2 text-sm">
          {feedState.error}
        </div>
      )}

      <div className="flex-1 min-h-0">
        <MacroReactGrid
          key={gridKey}
          ref={gridRef}
          columns={effectiveColumns}
          rowData={rowData}
          columnFormats={seedFormats}
          gridOptions={gridOptions}
          getRowId={getRowId}
        />
      </div>

      {sourceDialog}
    </div>
  );
}
